package com.example.schedule.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
public class Event {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String title;   // Заглавие на събитието

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime start;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime end;

    private String activity; // Тип на смяната (първа/втора/междинна)

    private String leaveType; // Тип отпуск ако има

    // НОВО ПОЛЕ: Флаг за автоматично генерирани смени
    // true = автоматично генерирана смяна
    // false или null = ръчно въведена смяна
    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated = false;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "employee_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private Employee employee;

    // Конструктори
    public Event() {
        this.isAutoGenerated = false; // По подразбиране е ръчно въведена
    }

    // Конструктор за всички полета без Builder/Lombok
    public Event(String title, LocalDateTime start, LocalDateTime end,
                 String activity, Employee employee, Boolean isAutoGenerated) {
        this.title = title;
        this.start = start;
        this.end = end;
        this.activity = activity;
        this.employee = employee;
        this.isAutoGenerated = isAutoGenerated;
    }

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public LocalDateTime getStart() {
        return start;
    }

    public void setStart(LocalDateTime start) {
        this.start = start;
    }

    public LocalDateTime getEnd() {
        return end;
    }

    public void setEnd(LocalDateTime end) {
        this.end = end;
    }

    public String getActivity() {
        return activity;
    }

    public void setActivity(String activity) {
        this.activity = activity;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public String getLeaveType() {
        return leaveType;
    }

    public void setLeaveType(String leaveType) {
        this.leaveType = leaveType;
    }

    public Boolean getIsAutoGenerated() {
        return isAutoGenerated;
    }

    public void setIsAutoGenerated(Boolean isAutoGenerated) {
        this.isAutoGenerated = isAutoGenerated;
    }
}