package com.example.schedule.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Entity
@NoArgsConstructor
@AllArgsConstructor
public class Event {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String title;   // Заглавие на събитието
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime start;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime end;

    // ПРЕМАХНАТО: Старото String activity поле
    // private String activity; // Това вече няма да се използва

    // НОВО: Връзка към Activity entity
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "activity_id", nullable = true) // Може да е null за отпуски
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private Activity activity;

    private String leaveType;

    // НОВО ПОЛЕ: Указва дали смяната е автоматично генерирана или ръчно създадена
    @Column(name = "is_auto_generated", nullable = false)
    private Boolean isAutoGenerated = false; // По подразбиране false (ръчно създадена)

    // Връзка към служителя
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "employee_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private Employee employee;

    // =====================================
    // GETTERS AND SETTERS
    // =====================================

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public LocalDateTime getStart() {
        return start;
    }

    public void setStart(LocalDateTime start) {
        this.start = start;
    }

    public LocalDateTime getEnd() {
        return end;
    }

    public void setEnd(LocalDateTime end) {
        this.end = end;
    }

    // НОВО: Getter и setter за Activity entity
    public Activity getActivity() {
        return activity;
    }

    public void setActivity(Activity activity) {
        this.activity = activity;
    }

    // ПОМОЩЕН МЕТОД: Връща името на activity за съвместимост с existing код
    public String getActivityName() {
        return activity != null ? activity.getName() : null;
    }

    // ПОМОЩЕН МЕТОД: Връща ID на activity
    public Long getActivityId() {
        return activity != null ? activity.getId() : null;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public String getLeaveType() {
        return leaveType;
    }

    public void setLeaveType(String leaveType) {
        this.leaveType = leaveType;
    }

    // Getter и setter за isAutoGenerated
    public Boolean getIsAutoGenerated() {
        return isAutoGenerated;
    }

    public void setIsAutoGenerated(Boolean isAutoGenerated) {
        this.isAutoGenerated = isAutoGenerated != null ? isAutoGenerated : false;
    }

    // =====================================
    // UTILITY МЕТОДИ
    // =====================================

    @Override
    public String toString() {
        return "Event{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", start=" + start +
                ", end=" + end +
                ", activity=" + (activity != null ? activity.getName() : "null") +
                ", leaveType='" + leaveType + '\'' +
                ", employee=" + (employee != null ? employee.getName() : "null") +
                ", isAutoGenerated=" + isAutoGenerated +
                '}';
    }
}