package com.example.schedule.service;

import com.example.schedule.entity.Employee;
import com.example.schedule.entity.Event;
import com.example.schedule.repository.EmployeeRepository;
import com.example.schedule.repository.EventRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.*;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.stream.Collectors;

/**
 * СЕРВИС ЗА АВТОМАТИЧНО ГЕНЕРИРАНЕ НА МЕСЕЧЕН ГРАФИК
 * Този сервис съдържа целия алгоритъм за създаване на оптимален работен график
 * съобразен с всички изисквания и ограничения
 */
@Service
public class AutoScheduleService {

    @Autowired
    private EmployeeRepository employeeRepository;

    @Autowired
    private EventRepository eventRepository;

    @Autowired
    private ValidationService validationService;

    // ========================================
    // КОНСТАНТИ ЗА РАБОТНИТЕ СМЕНИ
    // ========================================

    // Първа смяна: 06:00 - 14:30 (8.5 часа с 30 мин почивка)
    private static final LocalTime FIRST_SHIFT_START = LocalTime.of(6, 0);
    private static final LocalTime FIRST_SHIFT_END = LocalTime.of(14, 30);

    // Втора смяна: 13:30 - 22:00 (8.5 часа с 30 мин почивка)
    private static final LocalTime SECOND_SHIFT_START = LocalTime.of(13, 30);
    private static final LocalTime SECOND_SHIFT_END = LocalTime.of(22, 0);

    // Междинна смяна: 09:30 - 18:00 (8.5 часа с 30 мин почивка)
    private static final LocalTime INTERMEDIATE_SHIFT_START = LocalTime.of(9, 30);
    private static final LocalTime INTERMEDIATE_SHIFT_END = LocalTime.of(18, 0);

    // Ограничения
    private static final int MAX_CONSECUTIVE_WORK_DAYS = 6; // Максимум 6 последователни работни дни
    private static final int MIN_REST_HOURS = 12; // Минимум 12 часа почивка между смени

    /**
     * ГЛАВНА ФУНКЦИЯ: Генерира автоматичен график за даден месец
     *
     * @param year година
     * @param month месец (1-12)
     * @return съобщение за резултата
     */
    @Transactional
    public String generateMonthlySchedule(int year, int month) {
        System.out.println("========================================");
        System.out.println("🚀 СТАРТИРАНЕ НА АВТОМАТИЧНО ГЕНЕРИРАНЕ НА ГРАФИК");
        System.out.println("📅 Месец: " + month + "/" + year);
        System.out.println("========================================");

        try {
            // СТЪПКА 1: Изтриваме старите автоматично генерирани смени за месеца
            deleteAutoGeneratedShifts(year, month);

            // СТЪПКА 2: Зареждаме всички служители и техните договори
            List<Employee> employees = employeeRepository.findAll();
            if (employees.isEmpty()) {
                return "Няма налични служители за генериране на график";
            }

            System.out.println("📊 Намерени служители: " + employees.size());

            // СТЪПКА 3: Зареждаме ръчно въведените смени (те имат приоритет)
            Map<Long, List<Event>> manualShiftsByEmployee = loadManualShifts(year, month);
            System.out.println("✋ Ръчно въведени смени: " +
                    manualShiftsByEmployee.values().stream().mapToInt(List::size).sum());

            // СТЪПКА 4: Генерираме график за всеки ден от месеца
            LocalDate startDate = LocalDate.of(year, month, 1);
            LocalDate endDate = startDate.withDayOfMonth(startDate.lengthOfMonth());

            // Създаваме структура за съхранение на генерираните смени
            List<Event> generatedShifts = new ArrayList<>();

            // Обработваме всеки ден от месеца
            LocalDate currentDate = startDate;
            while (!currentDate.isAfter(endDate)) {
                System.out.println("\n📅 Обработка на дата: " + currentDate);

                // Генерираме смени за текущия ден
                List<Event> dailyShifts = generateDailyShifts(
                        currentDate,
                        employees,
                        manualShiftsByEmployee,
                        generatedShifts
                );

                generatedShifts.addAll(dailyShifts);
                currentDate = currentDate.plusDays(1);
            }

            // СТЪПКА 5: Записваме генерираните смени в базата данни
            for (Event shift : generatedShifts) {
                shift.setIsAutoGenerated(true);
                eventRepository.save(shift);
            }

            System.out.println("\n========================================");
            System.out.println("✅ УСПЕШНО ГЕНЕРИРАН ГРАФИК");
            System.out.println("📊 Общо генерирани смени: " + generatedShifts.size());
            System.out.println("========================================");

            return "Успешно генериран график за " + month + "/" + year +
                    ". Създадени " + generatedShifts.size() + " смени.";

        } catch (Exception e) {
            System.err.println("❌ ГРЕШКА при генериране на график: " + e.getMessage());
            e.printStackTrace();
            throw new RuntimeException("Грешка при генериране на график: " + e.getMessage());
        }
    }

    /**
     * Генерира смени за един конкретен ден
     * Това е сърцето на алгоритъма - тук се прилагат всички правила
     */
    private List<Event> generateDailyShifts(
            LocalDate date,
            List<Employee> allEmployees,
            Map<Long, List<Event>> manualShifts,
            List<Event> previouslyGenerated) {

        List<Event> dailyShifts = new ArrayList<>();

        // Подготвяме информация за всеки служител
        List<EmployeeScheduleInfo> employeeInfos = prepareEmployeeInfo(
                allEmployees, date, manualShifts, previouslyGenerated
        );

        // Сортираме служителите по приоритет
        // Приоритет имат тези с по-малко отработени часове и по-голям договор
        employeeInfos.sort((a, b) -> {
            // Първо сравняваме процента на покритие на месечната норма
            double coverageA = a.getMonthlyHoursCoverage();
            double coverageB = b.getMonthlyHoursCoverage();
            return Double.compare(coverageA, coverageB);
        });

        // Определяме колко служители са нужни за всяка смяна
        int totalAvailable = (int) employeeInfos.stream()
                .filter(EmployeeScheduleInfo::canWorkToday)
                .count();

        System.out.println("👥 Налични служители за деня: " + totalAvailable);

        if (totalAvailable == 0) {
            System.out.println("⚠️ ВНИМАНИЕ: Няма налични служители за " + date);
            return dailyShifts;
        }

        // Разпределяме служителите по смени
        int firstShiftCount = Math.max(1, totalAvailable / 3);
        int secondShiftCount = Math.max(1, totalAvailable / 3);
        int intermediateShiftCount = Math.max(1, totalAvailable - firstShiftCount - secondShiftCount);

        // Балансираме броя на първа и втора смяна
        if (Math.abs(firstShiftCount - secondShiftCount) > 1) {
            int avg = (firstShiftCount + secondShiftCount) / 2;
            firstShiftCount = avg;
            secondShiftCount = avg;
            intermediateShiftCount = totalAvailable - firstShiftCount - secondShiftCount;
        }

        System.out.println("📊 Разпределение: Първа=" + firstShiftCount +
                ", Втора=" + secondShiftCount +
                ", Междинна=" + intermediateShiftCount);

        // Назначаваме смени на служителите
        int assigned = 0;
        for (EmployeeScheduleInfo info : employeeInfos) {
            if (!info.canWorkToday()) {
                System.out.println("❌ " + info.employee.getName() + " не може да работи днес");
                continue;
            }

            Event shift = null;

            // Определяме коя смяна е най-подходяща за служителя
            if (assigned < firstShiftCount && info.canWorkShift("FIRST", date)) {
                shift = createShift(info.employee, date, "FIRST");
            } else if (assigned < firstShiftCount + secondShiftCount && info.canWorkShift("SECOND", date)) {
                shift = createShift(info.employee, date, "SECOND");
            } else if (assigned < totalAvailable && info.canWorkShift("INTERMEDIATE", date)) {
                shift = createShift(info.employee, date, "INTERMEDIATE");
            }

            if (shift != null) {
                dailyShifts.add(shift);
                assigned++;
                System.out.println("✅ Назначен " + info.employee.getName() +
                        " на " + shift.getActivity() + " смяна");
            }

            // Ако сме назначили достатъчно хора, спираме
            if (assigned >= totalAvailable) {
                break;
            }
        }

        // Проверяваме дали имаме поне по един човек на всяка смяна
        ensureMinimumCoverage(dailyShifts, employeeInfos, date);

        return dailyShifts;
    }

    /**
     * Подготвя информация за всеки служител -
     * колко часа е работил, кога може да работи и т.н.
     */
    private List<EmployeeScheduleInfo> prepareEmployeeInfo(
            List<Employee> employees,
            LocalDate targetDate,
            Map<Long, List<Event>> manualShifts,
            List<Event> generatedShifts) {

        List<EmployeeScheduleInfo> infos = new ArrayList<>();

        for (Employee employee : employees) {
            EmployeeScheduleInfo info = new EmployeeScheduleInfo();
            info.employee = employee;

            // Събираме всички смени на служителя (ръчни + генерирани)
            List<Event> allShifts = new ArrayList<>();

            // Добавяме ръчните смени
            if (manualShifts.containsKey(employee.getId())) {
                allShifts.addAll(manualShifts.get(employee.getId()));
            }

            // Добавяме вече генерираните смени
            allShifts.addAll(
                    generatedShifts.stream()
                            .filter(s -> s.getEmployee().getId().equals(employee.getId()))
                            .collect(Collectors.toList())
            );

            // Изчисляваме статистики
            info.calculateStats(allShifts, targetDate);

            infos.add(info);
        }

        return infos;
    }

    /**
     * Създава смяна за служител
     */
    private Event createShift(Employee employee, LocalDate date, String shiftType) {
        Event shift = new Event();
        shift.setEmployee(employee);
        shift.setActivity(shiftType);
        shift.setIsAutoGenerated(true);

        // Определяме часовете според типа смяна
        LocalTime startTime, endTime;
        String title;

        switch (shiftType) {
            case "FIRST":
                startTime = FIRST_SHIFT_START;
                endTime = FIRST_SHIFT_END;
                title = "Първа смяна";
                break;
            case "SECOND":
                startTime = SECOND_SHIFT_START;
                endTime = SECOND_SHIFT_END;
                title = "Втора смяна";
                break;
            case "INTERMEDIATE":
                startTime = INTERMEDIATE_SHIFT_START;
                endTime = INTERMEDIATE_SHIFT_END;
                title = "Междинна смяна";
                break;
            default:
                throw new IllegalArgumentException("Невалиден тип смяна: " + shiftType);
        }

        shift.setTitle(title + " - " + employee.getName());
        shift.setStart(LocalDateTime.of(date, startTime));
        shift.setEnd(LocalDateTime.of(date, endTime));

        return shift;
    }

    /**
     * Осигурява минимално покритие - поне един човек на всяка смяна
     */
    private void ensureMinimumCoverage(
            List<Event> dailyShifts,
            List<EmployeeScheduleInfo> employeeInfos,
            LocalDate date) {

        // Проверяваме кои смени липсват
        boolean hasFirst = dailyShifts.stream()
                .anyMatch(s -> "FIRST".equals(s.getActivity()));
        boolean hasSecond = dailyShifts.stream()
                .anyMatch(s -> "SECOND".equals(s.getActivity()));
        boolean hasIntermediate = dailyShifts.stream()
                .anyMatch(s -> "INTERMEDIATE".equals(s.getActivity()));

        // Опитваме се да добавим липсващите смени
        if (!hasFirst) {
            addMissingShift("FIRST", employeeInfos, dailyShifts, date);
        }
        if (!hasSecond) {
            addMissingShift("SECOND", employeeInfos, dailyShifts, date);
        }
        if (!hasIntermediate) {
            addMissingShift("INTERMEDIATE", employeeInfos, dailyShifts, date);
        }
    }
    /**
     * Добавя липсваща смяна като намира подходящ служител
     */
    private void addMissingShift(
            String shiftType,
            List<EmployeeScheduleInfo> employeeInfos,
            List<Event> dailyShifts,
            LocalDate date) {

        System.out.println("⚠️ Търсим служител за липсваща " + shiftType + " смяна");

        // Търсим служител който още не е назначен за деня
        Set<Long> assignedEmployeeIds = dailyShifts.stream()
                .map(s -> s.getEmployee().getId())
                .collect(Collectors.toSet());

        for (EmployeeScheduleInfo info : employeeInfos) {
            if (!assignedEmployeeIds.contains(info.employee.getId()) &&
                    info.canWorkShift(shiftType, date)) {

                Event shift = createShift(info.employee, date, shiftType);
                dailyShifts.add(shift);
                System.out.println("✅ Добавен " + info.employee.getName() +
                        " за покриване на " + shiftType + " смяна");
                break;
            }
        }
    }

    /**
     * Изтрива старите автоматично генерирани смени
     */
    private void deleteAutoGeneratedShifts(int year, int month) {
        LocalDate startDate = LocalDate.of(year, month, 1);
        LocalDate endDate = startDate.withDayOfMonth(startDate.lengthOfMonth());

        LocalDateTime startDateTime = startDate.atStartOfDay();
        LocalDateTime endDateTime = endDate.atTime(23, 59, 59);

        List<Event> autoGeneratedShifts = eventRepository.findAll().stream()
                .filter(e -> e.getIsAutoGenerated() != null && e.getIsAutoGenerated())
                .filter(e -> !e.getStart().isBefore(startDateTime) && !e.getStart().isAfter(endDateTime))
                .collect(Collectors.toList());

        System.out.println("🗑️ Изтриване на " + autoGeneratedShifts.size() +
                " стари автоматично генерирани смени");

        eventRepository.deleteAll(autoGeneratedShifts);
    }

    /**
     * Зарежда ръчно въведените смени за месеца
     */
    private Map<Long, List<Event>> loadManualShifts(int year, int month) {
        LocalDate startDate = LocalDate.of(year, month, 1);
        LocalDate endDate = startDate.withDayOfMonth(startDate.lengthOfMonth());

        LocalDateTime startDateTime = startDate.atStartOfDay();
        LocalDateTime endDateTime = endDate.atTime(23, 59, 59);

        List<Event> manualShifts = eventRepository.findAll().stream()
                .filter(e -> e.getIsAutoGenerated() == null || !e.getIsAutoGenerated())
                .filter(e -> !e.getStart().isBefore(startDateTime) && !e.getStart().isAfter(endDateTime))
                .collect(Collectors.toList());

        // Групираме по служител
        return manualShifts.stream()
                .collect(Collectors.groupingBy(e -> e.getEmployee().getId()));
    }

    /**
     * Вътрешен клас за съхранение на информация за графика на служител
     */
    private class EmployeeScheduleInfo {
        Employee employee;
        int totalMonthlyHours = 0;
        int consecutiveWorkDays = 0;
        LocalDate lastWorkDate = null;
        Event lastShift = null;
        List<Event> monthlyShifts = new ArrayList<>();

        /**
         * Изчислява статистиките за служителя
         */
        void calculateStats(List<Event> shifts, LocalDate targetDate) {
            // Филтрираме смените за текущия месец
            monthlyShifts = shifts.stream()
                    .filter(s -> s.getStart().getMonth() == targetDate.getMonth())
                    .sorted(Comparator.comparing(Event::getStart))
                    .collect(Collectors.toList());

            // Изчисляваме общите часове за месеца
            for (Event shift : monthlyShifts) {
                long hours = ChronoUnit.HOURS.between(shift.getStart(), shift.getEnd());
                totalMonthlyHours += hours;
            }

            // Намираме последната смяна и проверяваме за последователни дни
            if (!monthlyShifts.isEmpty()) {
                lastShift = monthlyShifts.get(monthlyShifts.size() - 1);
                lastWorkDate = lastShift.getStart().toLocalDate();

                // Броим последователните работни дни назад от последната дата
                consecutiveWorkDays = countConsecutiveWorkDays(shifts, lastWorkDate);
            }
        }

        /**
         * Проверява дали служителят може да работи днес
         */
        boolean canWorkToday() {
            // Проверка 1: Максимум 6 последователни работни дни
            if (consecutiveWorkDays >= MAX_CONSECUTIVE_WORK_DAYS) {
                return false;
            }

            // Проверка 2: Проверяваме месечната норма
            Integer contractHours = employee.getHourlyRate();
            if (contractHours == null) contractHours = 8;

            int maxMonthlyHours = getMaxMonthlyHours(contractHours);
            if (totalMonthlyHours >= maxMonthlyHours) {
                return false;
            }

            return true;
        }

        /**
         * Проверява дали служителят може да работи конкретна смяна
         */
        boolean canWorkShift(String shiftType, LocalDate date) {
            if (!canWorkToday()) return false;

            // Ако няма предишна смяна, може да работи всяка смяна
            if (lastShift == null) return true;

            // Проверяваме 12-часовото правило
            LocalDateTime newShiftStart;
            switch (shiftType) {
                case "FIRST":
                    newShiftStart = LocalDateTime.of(date, FIRST_SHIFT_START);
                    break;
                case "SECOND":
                    newShiftStart = LocalDateTime.of(date, SECOND_SHIFT_START);
                    break;
                case "INTERMEDIATE":
                    newShiftStart = LocalDateTime.of(date, INTERMEDIATE_SHIFT_START);
                    break;
                default:
                    return false;
            }

            long hoursSinceLastShift = ChronoUnit.HOURS.between(
                    lastShift.getEnd(), newShiftStart
            );

            return hoursSinceLastShift >= MIN_REST_HOURS;
        }

        /**
         * Изчислява процента на покритие на месечната норма
         */
        double getMonthlyHoursCoverage() {
            Integer contractHours = employee.getHourlyRate();
            if (contractHours == null) contractHours = 8;

            int targetMonthlyHours = getTargetMonthlyHours(contractHours);
            if (targetMonthlyHours == 0) return 0;

            return (double) totalMonthlyHours / targetMonthlyHours;
        }

        /**
         * Брои последователните работни дни
         */
        private int countConsecutiveWorkDays(List<Event> shifts, LocalDate fromDate) {
            int count = 0;
            LocalDate checkDate = fromDate;

            while (true) {
                LocalDate finalCheckDate = checkDate;
                boolean hasShiftOnDate = shifts.stream()
                        .anyMatch(s -> s.getStart().toLocalDate().equals(finalCheckDate));

                if (hasShiftOnDate) {
                    count++;
                    checkDate = checkDate.minusDays(1);
                } else {
                    break;
                }
            }

            return count;
        }
    }

    /**
     * Връща максималните месечни часове според договора
     */
    private int getMaxMonthlyHours(int contractHoursPerDay) {
        switch (contractHoursPerDay) {
            case 4:
                return 100; // Малко повече от 80 часа
            case 6:
                return 140; // Малко повече от 120 часа
            case 8:
                return 184; // Малко повече от 160 часа
            default:
                return 160;
        }
    }

    /**
     * Връща целевите месечни часове според договора
     */
    private int getTargetMonthlyHours(int contractHoursPerDay) {
        switch (contractHoursPerDay) {
            case 4:
                return 80;
            case 6:
                return 120;
            case 8:
                return 160;
            default:
                return 160;
        }
    }

    // ========================================
    // ДОПЪЛНИТЕЛНИ МЕТОДИ ЗА ОПТИМИЗАЦИЯ
    // ========================================

    /**
     * Балансира смените между служителите
     * Гарантира че всеки има приблизително равен брой първи, втори и междинни смени
     */
    private void balanceShiftTypes(List<EmployeeScheduleInfo> employeeInfos) {
        Map<Long, Map<String, Integer>> shiftCounts = new HashMap<>();

        // Броим колко от всеки тип смяна има всеки служител
        for (EmployeeScheduleInfo info : employeeInfos) {
            Map<String, Integer> counts = new HashMap<>();
            counts.put("FIRST", 0);
            counts.put("SECOND", 0);
            counts.put("INTERMEDIATE", 0);

            for (Event shift : info.monthlyShifts) {
                String type = shift.getActivity();
                counts.put(type, counts.get(type) + 1);
            }

            shiftCounts.put(info.employee.getId(), counts);
        }

        // Логиката за балансиране може да се разшири тук
        System.out.println("📊 Баланс на смените по тип:");
        for (EmployeeScheduleInfo info : employeeInfos) {
            Map<String, Integer> counts = shiftCounts.get(info.employee.getId());
            System.out.println("   " + info.employee.getName() + ": " +
                    "Първа=" + counts.get("FIRST") + ", " +
                    "Втора=" + counts.get("SECOND") + ", " +
                    "Междинна=" + counts.get("INTERMEDIATE"));
        }
    }

    /**
     * Проверява дали генерираният график е валиден
     * Използва се за финална проверка преди записване
     */
    private boolean validateGeneratedSchedule(List<Event> generatedShifts) {
        System.out.println("🔍 Валидация на генерирания график...");

        // Групираме по служител
        Map<Long, List<Event>> shiftsByEmployee = generatedShifts.stream()
                .collect(Collectors.groupingBy(e -> e.getEmployee().getId()));

        for (Map.Entry<Long, List<Event>> entry : shiftsByEmployee.entrySet()) {
            List<Event> employeeShifts = entry.getValue();
            employeeShifts.sort(Comparator.comparing(Event::getStart));

            // Проверка 1: 12 часа почивка между смени
            for (int i = 1; i < employeeShifts.size(); i++) {
                Event previousShift = employeeShifts.get(i - 1);
                Event currentShift = employeeShifts.get(i);

                long hoursBetween = ChronoUnit.HOURS.between(
                        previousShift.getEnd(), currentShift.getStart()
                );

                if (hoursBetween < MIN_REST_HOURS) {
                    System.err.println("❌ Нарушено 12-часово правило за почивка!");
                    return false;
                }
            }

            // Проверка 2: Максимум 6 последователни работни дни
            int consecutiveDays = 1;
            LocalDate lastDate = employeeShifts.get(0).getStart().toLocalDate();

            for (int i = 1; i < employeeShifts.size(); i++) {
                LocalDate currentDate = employeeShifts.get(i).getStart().toLocalDate();

                if (currentDate.equals(lastDate.plusDays(1))) {
                    consecutiveDays++;
                    if (consecutiveDays > MAX_CONSECUTIVE_WORK_DAYS) {
                        System.err.println("❌ Надвишен максимум от 6 последователни работни дни!");
                        return false;
                    }
                } else {
                    consecutiveDays = 1;
                }

                lastDate = currentDate;
            }
        }

        System.out.println("✅ Валидацията премина успешно!");
        return true;
    }

    /**
     * Генерира статистика за създадения график
     */
    public Map<String, Object> generateScheduleStatistics(int year, int month) {
        Map<String, Object> stats = new HashMap<>();

        LocalDate startDate = LocalDate.of(year, month, 1);
        LocalDate endDate = startDate.withDayOfMonth(startDate.lengthOfMonth());

        LocalDateTime startDateTime = startDate.atStartOfDay();
        LocalDateTime endDateTime = endDate.atTime(23, 59, 59);

        List<Event> allEvents = eventRepository.findAll().stream()
                .filter(e -> !e.getStart().isBefore(startDateTime) && !e.getStart().isAfter(endDateTime))
                .collect(Collectors.toList());

        long autoGenerated = allEvents.stream()
                .filter(e -> e.getIsAutoGenerated() != null && e.getIsAutoGenerated())
                .count();

        long manual = allEvents.size() - autoGenerated;

        stats.put("totalShifts", allEvents.size());
        stats.put("autoGeneratedShifts", autoGenerated);
        stats.put("manualShifts", manual);
        stats.put("month", month);
        stats.put("year", year);

        return stats;
    }
}