package com.example.schedule.service;

import com.example.schedule.entity.Employee;
import com.example.schedule.entity.Event;
import com.example.schedule.repository.EmployeeRepository;
import com.example.schedule.repository.EventRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.DayOfWeek;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class ScheduleGeneratorService {

    @Autowired
    private EmployeeRepository employeeRepository;

    @Autowired
    private EventRepository eventRepository;

    // Константи за смените
    private static final LocalTime FIRST_SHIFT_START = LocalTime.of(6, 0);
    private static final LocalTime FIRST_SHIFT_END = LocalTime.of(14, 30);

    private static final LocalTime SECOND_SHIFT_START = LocalTime.of(13, 30);
    private static final LocalTime SECOND_SHIFT_END = LocalTime.of(22, 0);

    private static final LocalTime MIDDLE_SHIFT_START = LocalTime.of(9, 30);
    private static final LocalTime MIDDLE_SHIFT_END = LocalTime.of(18, 0);

    // Енум за типовете смени
    public enum ShiftType {
        FIRST("First Shift", FIRST_SHIFT_START, FIRST_SHIFT_END),
        SECOND("Second Shift", SECOND_SHIFT_START, SECOND_SHIFT_END),
        MIDDLE("Middle Shift", MIDDLE_SHIFT_START, MIDDLE_SHIFT_END);

        private final String name;
        private final LocalTime startTime;
        private final LocalTime endTime;

        ShiftType(String name, LocalTime startTime, LocalTime endTime) {
            this.name = name;
            this.startTime = startTime;
            this.endTime = endTime;
        }

        public String getName() { return name; }
        public LocalTime getStartTime() { return startTime; }
        public LocalTime getEndTime() { return endTime; }
    }

    /**
     * ГЛАВНА ФУНКЦИЯ: Генерира автоматично график за месеца
     * ОБНОВЕНА ЗА 7-ДНЕВНА РАБОТА И БАЛАНСИРАНИ СМЕНИ
     */
    @Transactional
    public int generateMonthlySchedule(int year, int month) {
        System.out.println("🚀 === ЗАПОЧВА АВТОМАТИЧНО ГЕНЕРИРАНЕ НА 7-ДНЕВЕН ГРАФИК ===");
        System.out.println(String.format("📅 Период: %02d/%d", month, year));

        // СТЪПКА 1: Вземаме всички активни служители
        List<Employee> allEmployees = employeeRepository.findAll();
        if (allEmployees.isEmpty()) {
            System.out.println("❌ Няма налични служители за генериране на график");
            return 0;
        }
        System.out.println(String.format("👥 Намерени %d служители", allEmployees.size()));

        // СТЪПКА 2: Изтриваме стари автоматично генерирани смени за месеца
        deleteAutoGeneratedShiftsForMonth(year, month);

        // СТЪПКА 3: Генерираме ВСИЧКИ дни за месеца (без изключения)
        List<LocalDate> allDaysInMonth = generateAllDaysForMonth(year, month);
        System.out.println(String.format("📊 Месецът има %d дни (включително уикенди)", allDaysInMonth.size()));

        // СТЪПКА 4: Получаваме съществуващи ръчно създадени смени
        Map<LocalDate, List<Event>> existingManualShifts = getExistingManualShiftsByDate(year, month);
        System.out.println(String.format("📌 Намерени ръчно създадени смени за %d дни", existingManualShifts.size()));

        // СТЪПКА 5: Анализираме капацитета и нуждите
        ScheduleAnalysis analysis = analyzeSchedulingNeeds(allEmployees, allDaysInMonth, existingManualShifts);
        System.out.println(String.format("📊 Анализ: %d дни за покриване, %d общо часа",
                analysis.getDaysToSchedule(), analysis.getTotalHoursNeeded()));

        // СТЪПКА 6: Създаваме оптимален график
        Map<LocalDate, DailySchedule> monthlySchedule = createOptimalMonthlySchedule(
                allEmployees, allDaysInMonth, existingManualShifts, analysis);

        // СТЪПКА 7: Генерираме и записваме смените
        List<Event> generatedShifts = createEventsFromSchedule(monthlySchedule);
        eventRepository.saveAll(generatedShifts);

        System.out.println(String.format("🎯 ГЕНЕРИРАНЕТО ЗАВЪРШИ УСПЕШНО! Общо смени: %d", generatedShifts.size()));
        return generatedShifts.size();
    }

    /**
     * НОВА ФУНКЦИЯ: Генерира всички дни в месеца (включително уикенди)
     */
    private List<LocalDate> generateAllDaysForMonth(int year, int month) {
        List<LocalDate> allDays = new ArrayList<>();
        LocalDate date = LocalDate.of(year, month, 1);
        LocalDate endOfMonth = date.withDayOfMonth(date.lengthOfMonth());

        while (!date.isAfter(endOfMonth)) {
            allDays.add(date);
            date = date.plusDays(1);
        }

        System.out.println(String.format("📅 Генерирани %d дни: %s - %s",
                allDays.size(), allDays.get(0), allDays.get(allDays.size()-1)));
        return allDays;
    }

    /**
     * НОВА ФУНКЦИЯ: Получава съществуващи ръчни смени групирани по дни
     */
    private Map<LocalDate, List<Event>> getExistingManualShiftsByDate(int year, int month) {
        LocalDate startOfMonth = LocalDate.of(year, month, 1);
        LocalDate endOfMonth = startOfMonth.withDayOfMonth(startOfMonth.lengthOfMonth());

        LocalDateTime startDateTime = startOfMonth.atStartOfDay();
        LocalDateTime endDateTime = endOfMonth.atTime(23, 59, 59);

        List<Event> manualEvents = eventRepository.findAll().stream()
                .filter(event -> event.getIsAutoGenerated() == null || !event.getIsAutoGenerated())
                .filter(event -> event.getStart() != null)
                .filter(event -> !event.getStart().isBefore(startDateTime) && !event.getStart().isAfter(endDateTime))
                .filter(event -> event.getLeaveType() == null) // Изключваме отпуски
                .collect(Collectors.toList());

        return manualEvents.stream()
                .collect(Collectors.groupingBy(event -> event.getStart().toLocalDate()));
    }

    /**
     * НОВА ФУНКЦИЯ: Анализира нуждите за планиране
     */
    private ScheduleAnalysis analyzeSchedulingNeeds(List<Employee> employees,
                                                    List<LocalDate> allDays,
                                                    Map<LocalDate, List<Event>> existingShifts) {

        ScheduleAnalysis analysis = new ScheduleAnalysis();

        // Изчисляваме общия капацитет на служителите
        int totalEmployeeCapacity = 0;
        for (Employee emp : employees) {
            int contractHours = emp.getHourlyRate() != null ? emp.getHourlyRate() : 8;
            int daysPerWeek = Math.round((contractHours * 7) / 8.0f); // Колко дни може да работи в седмица
            int daysPerMonth = (daysPerWeek * allDays.size()) / 7;
            totalEmployeeCapacity += daysPerMonth;
        }

        // Изчисляваме минималните нужди (3 смени на ден - 1 първа, 1 втора, 1 междинна)
        int minShiftsNeeded = allDays.size() * 3;

        // Изчисляваме оптималните нужди (равномерно разпределение)
        int optimalShiftsPerDay = Math.max(3, employees.size() / 3); // Поне 3, или 1/3 от служителите
        int optimalTotalShifts = allDays.size() * optimalShiftsPerDay;

        analysis.setTotalEmployees(employees.size());
        analysis.setTotalDays(allDays.size());
        analysis.setEmployeeCapacity(totalEmployeeCapacity);
        analysis.setMinShiftsNeeded(minShiftsNeeded);
        analysis.setOptimalShiftsNeeded(Math.min(optimalTotalShifts, totalEmployeeCapacity));
        analysis.setExistingShifts(existingShifts.values().stream().mapToInt(List::size).sum());

        System.out.println(String.format("📊 Анализ на капацитета:"));
        System.out.println(String.format("   👥 Служители: %d", analysis.getTotalEmployees()));
        System.out.println(String.format("   📅 Дни: %d", analysis.getTotalDays()));
        System.out.println(String.format("   💪 Капацитет: %d смени", analysis.getEmployeeCapacity()));
        System.out.println(String.format("   🎯 Минимум: %d смени", analysis.getMinShiftsNeeded()));
        System.out.println(String.format("   ⭐ Оптимум: %d смени", analysis.getOptimalShiftsNeeded()));
        System.out.println(String.format("   📌 Съществуващи: %d смени", analysis.getExistingShifts()));

        return analysis;
    }

    /**
     * КЛЮЧОВА ФУНКЦИЯ: Създава оптимален месечен график
     */
    private Map<LocalDate, DailySchedule> createOptimalMonthlySchedule(
            List<Employee> employees,
            List<LocalDate> allDays,
            Map<LocalDate, List<Event>> existingShifts,
            ScheduleAnalysis analysis) {

        Map<LocalDate, DailySchedule> schedule = new HashMap<>();
        Map<Employee, Integer> employeeWorkDays = new HashMap<>();
        Map<Employee, Set<LocalDate>> employeeRestDays = new HashMap<>();

        // Инициализираме броячи за всеки служител
        for (Employee emp : employees) {
            employeeWorkDays.put(emp, 0);
            employeeRestDays.put(emp, new HashSet<>());
        }

        // СТЪПКА 1: Създаваме ротационна схема за почивните дни
        Map<Employee, Set<LocalDate>> rotationalRestDays = createRotationalRestDays(employees, allDays);

        // СТЪПКА 2: За всеки ден планираме смените
        for (LocalDate day : allDays) {
            DailySchedule dailySchedule = planDailyShifts(day, employees, existingShifts.get(day),
                    rotationalRestDays, analysis);
            schedule.put(day, dailySchedule);

            // Обновяваме броячите
            for (Employee emp : dailySchedule.getAllAssignedEmployees()) {
                employeeWorkDays.put(emp, employeeWorkDays.get(emp) + 1);
            }
        }

        // СТЪПКА 3: Логваме резултатите
        logScheduleResults(schedule, employeeWorkDays);

        return schedule;
    }

    /**
     * НОВА ФУНКЦИЯ: Създава ротационна схема за почивните дни
     */
    private Map<Employee, Set<LocalDate>> createRotationalRestDays(List<Employee> employees, List<LocalDate> allDays) {
        Map<Employee, Set<LocalDate>> restDays = new HashMap<>();

        // Различни шаблони за почивни дни
        List<List<DayOfWeek>> restPatterns = Arrays.asList(
                Arrays.asList(DayOfWeek.SATURDAY, DayOfWeek.SUNDAY),      // Класически уикенд
                Arrays.asList(DayOfWeek.MONDAY, DayOfWeek.TUESDAY),       // Понеделник-вторник
                Arrays.asList(DayOfWeek.WEDNESDAY, DayOfWeek.THURSDAY),   // Сряда-четвъртък
                Arrays.asList(DayOfWeek.FRIDAY, DayOfWeek.SATURDAY),      // Петък-събота
                Arrays.asList(DayOfWeek.SUNDAY, DayOfWeek.MONDAY),        // Неделя-понеделник
                Arrays.asList(DayOfWeek.TUESDAY, DayOfWeek.WEDNESDAY),    // Вторник-сряда
                Arrays.asList(DayOfWeek.THURSDAY, DayOfWeek.FRIDAY)       // Четвъртък-петък
        );

        for (int i = 0; i < employees.size(); i++) {
            Employee emp = employees.get(i);
            List<DayOfWeek> pattern = restPatterns.get(i % restPatterns.size()); // Ротация на шаблоните

            Set<LocalDate> empRestDays = new HashSet<>();
            for (LocalDate day : allDays) {
                if (pattern.contains(day.getDayOfWeek())) {
                    empRestDays.add(day);
                }
            }

            restDays.put(emp, empRestDays);
            System.out.println(String.format("👤 %s: почива %s (%d дни)",
                    emp.getName(), pattern, empRestDays.size()));
        }

        return restDays;
    }

    /**
     * КЛЮЧОВА ФУНКЦИЯ: Планира смените за един ден
     */
    private DailySchedule planDailyShifts(LocalDate day,
                                          List<Employee> allEmployees,
                                          List<Event> existingShifts,
                                          Map<Employee, Set<LocalDate>> restDays,
                                          ScheduleAnalysis analysis) {

        DailySchedule dailySchedule = new DailySchedule(day);

        // СТЪПКА 1: Добавяме съществуващите ръчни смени
        if (existingShifts != null) {
            for (Event shift : existingShifts) {
                ShiftType type = determineShiftType(shift);
                dailySchedule.addExistingShift(shift.getEmployee(), type);
            }
        }

        // СТЪПКА 2: Определяме кои служители са налични днес
        List<Employee> availableEmployees = allEmployees.stream()
                .filter(emp -> !restDays.getOrDefault(emp, Collections.emptySet()).contains(day))
                .filter(emp -> !dailySchedule.isEmployeeAlreadyScheduled(emp))
                .collect(Collectors.toList());

        // СТЪПКА 3: Изчисляваме колко смени трябва да добавим
        int neededFirstShifts = Math.max(1, (availableEmployees.size() / 3)) - dailySchedule.getFirstShiftCount();
        int neededSecondShifts = Math.max(1, (availableEmployees.size() / 3)) - dailySchedule.getSecondShiftCount();
        int neededMiddleShifts = Math.max(1, 1) - dailySchedule.getMiddleShiftCount(); // Винаги поне 1

        // СТЪПКА 4: Разпределяме служителите по смени
        Collections.shuffle(availableEmployees); // Случайно разбъркване за справедливост

        Iterator<Employee> empIterator = availableEmployees.iterator();

        // Първо добавяме междинните смени (приоритет)
        while (neededMiddleShifts > 0 && empIterator.hasNext()) {
            Employee emp = empIterator.next();
            dailySchedule.addGeneratedShift(emp, ShiftType.MIDDLE);
            neededMiddleShifts--;
        }

        // След това балансираме първа и втора смяна
        while ((neededFirstShifts > 0 || neededSecondShifts > 0) && empIterator.hasNext()) {
            Employee emp = empIterator.next();

            if (neededFirstShifts >= neededSecondShifts && neededFirstShifts > 0) {
                dailySchedule.addGeneratedShift(emp, ShiftType.FIRST);
                neededFirstShifts--;
            } else if (neededSecondShifts > 0) {
                dailySchedule.addGeneratedShift(emp, ShiftType.SECOND);
                neededSecondShifts--;
            }
        }

        System.out.println(String.format("📅 %s: %d първи, %d втори, %d междинни (общо %d)",
                day, dailySchedule.getFirstShiftCount(), dailySchedule.getSecondShiftCount(),
                dailySchedule.getMiddleShiftCount(), dailySchedule.getTotalShiftCount()));

        return dailySchedule;
    }

    /**
     * ПОМОЩНА ФУНКЦИЯ: Определя типа смяна по часове
     */
    private ShiftType determineShiftType(Event event) {
        LocalTime startTime = event.getStart().toLocalTime();

        if (startTime.equals(FIRST_SHIFT_START)) return ShiftType.FIRST;
        if (startTime.equals(SECOND_SHIFT_START)) return ShiftType.SECOND;
        if (startTime.equals(MIDDLE_SHIFT_START)) return ShiftType.MIDDLE;

        // Fallback логика
        if (startTime.isBefore(LocalTime.of(10, 0))) return ShiftType.FIRST;
        if (startTime.isAfter(LocalTime.of(13, 0))) return ShiftType.SECOND;
        return ShiftType.MIDDLE;
    }

    /**
     * ФУНКЦИЯ: Създава Event обекти от планирания график
     */
    private List<Event> createEventsFromSchedule(Map<LocalDate, DailySchedule> schedule) {
        List<Event> events = new ArrayList<>();

        for (Map.Entry<LocalDate, DailySchedule> entry : schedule.entrySet()) {
            LocalDate date = entry.getKey();
            DailySchedule daily = entry.getValue();

            // Създаваме събития за всички генерирани смени
            for (Map.Entry<Employee, ShiftType> shiftEntry : daily.getGeneratedShifts().entrySet()) {
                Employee emp = shiftEntry.getKey();
                ShiftType shiftType = shiftEntry.getValue();

                Event event = new Event();
                event.setTitle(emp.getName().split(" ")[0]); // Първото име
                event.setStart(date.atTime(shiftType.getStartTime()));
                event.setEnd(date.atTime(shiftType.getEndTime()));
                event.setActivity("Auto-generated " + shiftType.getName());
                event.setEmployee(emp);
                event.setIsAutoGenerated(true);

                events.add(event);
            }
        }

        return events;
    }

    /**
     * ФУНКЦИЯ: Логва резултатите от планирането
     */
    private void logScheduleResults(Map<LocalDate, DailySchedule> schedule, Map<Employee, Integer> workDays) {
        System.out.println("\n📊 === РЕЗУЛТАТИ ОТ ПЛАНИРАНЕТО ===");

        // Статистика по служители
        for (Map.Entry<Employee, Integer> entry : workDays.entrySet()) {
            Employee emp = entry.getKey();
            int days = entry.getValue();
            int contractHours = emp.getHourlyRate() != null ? emp.getHourlyRate() : 8;
            System.out.println(String.format("👤 %s (договор %dч): %d работни дни",
                    emp.getName(), contractHours, days));
        }

        // Статистика по дни
        int totalFirstShifts = 0, totalSecondShifts = 0, totalMiddleShifts = 0;
        for (DailySchedule daily : schedule.values()) {
            totalFirstShifts += daily.getFirstShiftCount();
            totalSecondShifts += daily.getSecondShiftCount();
            totalMiddleShifts += daily.getMiddleShiftCount();
        }

        System.out.println(String.format("\n📈 Общо смени: %d първи, %d втори, %d междинни",
                totalFirstShifts, totalSecondShifts, totalMiddleShifts));
        System.out.println("✅ ПЛАНИРАНЕТО ЗАВЪРШИ!\n");
    }

    /**
     * ФУНКЦИЯ: Изтрива автоматично генерирани смени за даден месец
     */
    private void deleteAutoGeneratedShiftsForMonth(int year, int month) {
        LocalDate startOfMonth = LocalDate.of(year, month, 1);
        LocalDate endOfMonth = startOfMonth.withDayOfMonth(startOfMonth.lengthOfMonth());

        LocalDateTime startDateTime = startOfMonth.atStartOfDay();
        LocalDateTime endDateTime = endOfMonth.atTime(23, 59, 59);

        List<Event> autoGeneratedEvents = eventRepository.findAll().stream()
                .filter(event -> event.getIsAutoGenerated() != null && event.getIsAutoGenerated())
                .filter(event -> event.getStart() != null)
                .filter(event -> !event.getStart().isBefore(startDateTime) && !event.getStart().isAfter(endDateTime))
                .collect(Collectors.toList());

        if (!autoGeneratedEvents.isEmpty()) {
            eventRepository.deleteAll(autoGeneratedEvents);
            System.out.println(String.format("🗑️  Изтрити %d стари автоматично генерирани смени", autoGeneratedEvents.size()));
        }
    }

    // ============================================================================
    // ПОМОЩНИ КЛАСОВЕ ЗА ОРГАНИЗАЦИЯ НА ДАННИТЕ
    // ============================================================================

    /**
     * КЛАС: Анализ на нуждите за планиране
     */
    public static class ScheduleAnalysis {
        private int totalEmployees;
        private int totalDays;
        private int employeeCapacity;
        private int minShiftsNeeded;
        private int optimalShiftsNeeded;
        private int existingShifts;

        // Getters и setters
        public int getTotalEmployees() { return totalEmployees; }
        public void setTotalEmployees(int totalEmployees) { this.totalEmployees = totalEmployees; }

        public int getTotalDays() { return totalDays; }
        public void setTotalDays(int totalDays) { this.totalDays = totalDays; }

        public int getEmployeeCapacity() { return employeeCapacity; }
        public void setEmployeeCapacity(int employeeCapacity) { this.employeeCapacity = employeeCapacity; }

        public int getMinShiftsNeeded() { return minShiftsNeeded; }
        public void setMinShiftsNeeded(int minShiftsNeeded) { this.minShiftsNeeded = minShiftsNeeded; }

        public int getOptimalShiftsNeeded() { return optimalShiftsNeeded; }
        public void setOptimalShiftsNeeded(int optimalShiftsNeeded) { this.optimalShiftsNeeded = optimalShiftsNeeded; }

        public int getExistingShifts() { return existingShifts; }
        public void setExistingShifts(int existingShifts) { this.existingShifts = existingShifts; }

        public int getDaysToSchedule() { return totalDays; }
        public int getTotalHoursNeeded() { return optimalShiftsNeeded * 8; }
    }

    /**
     * КЛАС: График за един ден
     */
    public static class DailySchedule {
        private LocalDate date;
        private Map<Employee, ShiftType> existingShifts = new HashMap<>();
        private Map<Employee, ShiftType> generatedShifts = new HashMap<>();

        public DailySchedule(LocalDate date) {
            this.date = date;
        }

        public void addExistingShift(Employee employee, ShiftType shiftType) {
            existingShifts.put(employee, shiftType);
        }

        public void addGeneratedShift(Employee employee, ShiftType shiftType) {
            generatedShifts.put(employee, shiftType);
        }

        public boolean isEmployeeAlreadyScheduled(Employee employee) {
            return existingShifts.containsKey(employee) || generatedShifts.containsKey(employee);
        }

        public Set<Employee> getAllAssignedEmployees() {
            Set<Employee> all = new HashSet<>(existingShifts.keySet());
            all.addAll(generatedShifts.keySet());
            return all;
        }

        public int getFirstShiftCount() {
            return countShiftsOfType(ShiftType.FIRST);
        }

        public int getSecondShiftCount() {
            return countShiftsOfType(ShiftType.SECOND);
        }

        public int getMiddleShiftCount() {
            return countShiftsOfType(ShiftType.MIDDLE);
        }

        public int getTotalShiftCount() {
            return existingShifts.size() + generatedShifts.size();
        }

        private int countShiftsOfType(ShiftType type) {
            int count = 0;
            count += (int) existingShifts.values().stream().filter(t -> t == type).count();
            count += (int) generatedShifts.values().stream().filter(t -> t == type).count();
            return count;
        }

        // Getters
        public LocalDate getDate() { return date; }
        public Map<Employee, ShiftType> getExistingShifts() { return existingShifts; }
        public Map<Employee, ShiftType> getGeneratedShifts() { return generatedShifts; }
    }
}