package com.example.schedule.service;

import com.example.schedule.entity.Employee;
import com.example.schedule.entity.Event;
import com.example.schedule.repository.EmployeeRepository;
import com.example.schedule.repository.EventRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.DayOfWeek;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class ScheduleGeneratorService {

    @Autowired
    private EmployeeRepository employeeRepository;

    @Autowired
    private EventRepository eventRepository;

    // Константи за смените
    private static final LocalTime FIRST_SHIFT_START = LocalTime.of(6, 0);
    private static final LocalTime FIRST_SHIFT_END = LocalTime.of(14, 30);

    private static final LocalTime SECOND_SHIFT_START = LocalTime.of(13, 30);
    private static final LocalTime SECOND_SHIFT_END = LocalTime.of(22, 0);

    private static final LocalTime MIDDLE_SHIFT_START = LocalTime.of(9, 30);
    private static final LocalTime MIDDLE_SHIFT_END = LocalTime.of(18, 0);

    // Енум за типовете смени
    public enum ShiftType {
        FIRST("First Shift", FIRST_SHIFT_START, FIRST_SHIFT_END),
        SECOND("Second Shift", SECOND_SHIFT_START, SECOND_SHIFT_END),
        MIDDLE("Middle Shift", MIDDLE_SHIFT_START, MIDDLE_SHIFT_END);

        private final String name;
        private final LocalTime startTime;
        private final LocalTime endTime;

        ShiftType(String name, LocalTime startTime, LocalTime endTime) {
            this.name = name;
            this.startTime = startTime;
            this.endTime = endTime;
        }

        public String getName() { return name; }
        public LocalTime getStartTime() { return startTime; }
        public LocalTime getEndTime() { return endTime; }
    }

    /**
     * ГЛАВНА ФУНКЦИЯ: Генерира автоматично график за месеца
     * @param year Година за генериране
     * @param month Месец за генериране (1-12)
     * @return Брой генерирани смени
     */
    @Transactional
    public int generateMonthlySchedule(int year, int month) {
        System.out.println("🚀 === ЗАПОЧВА АВТОМАТИЧНО ГЕНЕРИРАНЕ НА ГРАФИК ===");
        System.out.println(String.format("📅 Период: %02d/%d", month, year));

        // СТЪПКА 1: Вземаме всички активни служители
        List<Employee> allEmployees = employeeRepository.findAll();
        if (allEmployees.isEmpty()) {
            System.out.println("❌ Няма налични служители за генериране на график");
            return 0;
        }
        System.out.println(String.format("👥 Намерени %d служители", allEmployees.size()));

        // СТЪПКА 2: Изтриваме стари автоматично генерирани смени за месеца
        deleteAutoGeneratedShiftsForMonth(year, month);

        // СТЪПКА 3: Генерираме работни дни за месеца (без уикенди)
        List<LocalDate> workingDays = generateWorkingDaysForMonth(year, month);
        System.out.println(String.format("📊 Генерирани %d работни дни", workingDays.size()));

        // СТЪПКА 4: За всеки служител генерираме индивидуален график
        int totalGeneratedShifts = 0;
        for (Employee employee : allEmployees) {
            int shiftsForEmployee = generateScheduleForEmployee(employee, workingDays, year, month);
            totalGeneratedShifts += shiftsForEmployee;
            System.out.println(String.format("✅ Служител %s: %d смени",
                    employee.getName(), shiftsForEmployee));
        }

        System.out.println(String.format("🎯 ГЕНЕРИРАНЕТО ЗАВЪРШИ УСПЕШНО! Общо смени: %d", totalGeneratedShifts));
        return totalGeneratedShifts;
    }

    /**
     * ФУНКЦИЯ: Изтрива автоматично генерирани смени за даден месец
     * Запазва ръчно създадените смени
     */
    private void deleteAutoGeneratedShiftsForMonth(int year, int month) {
        LocalDate startOfMonth = LocalDate.of(year, month, 1);
        LocalDate endOfMonth = startOfMonth.withDayOfMonth(startOfMonth.lengthOfMonth());

        LocalDateTime startDateTime = startOfMonth.atStartOfDay();
        LocalDateTime endDateTime = endOfMonth.atTime(23, 59, 59);

        // Намираме всички автоматично генерирани събития за месеца
        List<Event> autoGeneratedEvents = eventRepository.findAll().stream()
                .filter(event -> event.getIsAutoGenerated() != null && event.getIsAutoGenerated())
                .filter(event -> event.getStart() != null)
                .filter(event -> !event.getStart().isBefore(startDateTime) && !event.getStart().isAfter(endDateTime))
                .collect(Collectors.toList());

        if (!autoGeneratedEvents.isEmpty()) {
            eventRepository.deleteAll(autoGeneratedEvents);
            System.out.println(String.format("🗑️  Изтрити %d стари автоматично генерирани смени", autoGeneratedEvents.size()));
        }
    }

    /**
     * ФУНКЦИЯ: Генерира работни дни за месеца (понеделник-петък)
     */
    private List<LocalDate> generateWorkingDaysForMonth(int year, int month) {
        List<LocalDate> workingDays = new ArrayList<>();
        LocalDate date = LocalDate.of(year, month, 1);
        LocalDate endOfMonth = date.withDayOfMonth(date.lengthOfMonth());

        while (!date.isAfter(endOfMonth)) {
            // Включваме само работни дни (понеделник-петък)
            if (date.getDayOfWeek() != DayOfWeek.SATURDAY && date.getDayOfWeek() != DayOfWeek.SUNDAY) {
                workingDays.add(date);
            }
            date = date.plusDays(1);
        }

        return workingDays;
    }

    /**
     * ФУНКЦИЯ: Генерира график за конкретен служител
     */
    private int generateScheduleForEmployee(Employee employee, List<LocalDate> workingDays, int year, int month) {
        System.out.println(String.format("👤 Генериране за %s (договор: %dч/ден)",
                employee.getName(), employee.getHourlyRate()));

        // СТЪПКА 1: Определяме колко дни трябва да работи според договора
        int contractHours = employee.getHourlyRate() != null ? employee.getHourlyRate() : 8;
        int workDaysNeeded = calculateWorkDaysNeeded(contractHours, workingDays.size());

        System.out.println(String.format("📋 Необходими работни дни: %d от %d налични",
                workDaysNeeded, workingDays.size()));

        // СТЪПКА 2: Получаваме съществуващи ръчно създадени смени за служителя
        List<Event> existingManualShifts = getExistingManualShifts(employee, year, month);
        Set<LocalDate> occupiedDates = existingManualShifts.stream()
                .map(event -> event.getStart().toLocalDate())
                .collect(Collectors.toSet());

        System.out.println(String.format("📌 Ръчно създадени смени: %d", existingManualShifts.size()));

        // СТЪПКА 3: Филтрираме работните дни (изключваме заетите)
        List<LocalDate> availableDays = workingDays.stream()
                .filter(date -> !occupiedDates.contains(date))
                .collect(Collectors.toList());

        // СТЪПКА 4: Изчисляваме колко още дни трябва да генерираме
        int additionalDaysNeeded = Math.max(0, workDaysNeeded - existingManualShifts.size());
        additionalDaysNeeded = Math.min(additionalDaysNeeded, availableDays.size());

        if (additionalDaysNeeded == 0) {
            System.out.println("✅ Служителят вече има достатъчно смени");
            return 0;
        }

        // СТЪПКА 5: Избираме дни за работа, спазвайки ограниченията
        List<LocalDate> selectedDays = selectWorkDaysWithConstraints(availableDays, additionalDaysNeeded, occupiedDates);

        // СТЪПКА 6: Разпределяме смените балансирано
        List<Event> generatedShifts = createBalancedShifts(employee, selectedDays);

        // СТЪПКА 7: Записваме в базата данни
        eventRepository.saveAll(generatedShifts);

        return generatedShifts.size();
    }

    /**
     * ФУНКЦИЯ: Изчислява колко дни трябва да работи служителят според договора
     */
    private int calculateWorkDaysNeeded(int contractHours, int totalWorkingDays) {
        // Логика: служител с 8ч договор работи всички дни
        // служител с 4ч договор работи половината дни, и т.н.
        double workRatio = contractHours / 8.0; // 8 часа е пълен работен ден
        int daysNeeded = (int) Math.round(totalWorkingDays * workRatio);

        // Минимум 2 дни, максимум всички налични дни
        return Math.max(2, Math.min(daysNeeded, totalWorkingDays));
    }

    /**
     * ФУНКЦИЯ: Получава съществуващи ръчно създадени смени за служителя
     */
    private List<Event> getExistingManualShifts(Employee employee, int year, int month) {
        LocalDate startOfMonth = LocalDate.of(year, month, 1);
        LocalDate endOfMonth = startOfMonth.withDayOfMonth(startOfMonth.lengthOfMonth());

        LocalDateTime startDateTime = startOfMonth.atStartOfDay();
        LocalDateTime endDateTime = endOfMonth.atTime(23, 59, 59);

        return eventRepository.findAll().stream()
                .filter(event -> employee.getId().equals(event.getEmployee().getId()))
                .filter(event -> event.getIsAutoGenerated() == null || !event.getIsAutoGenerated()) // Ръчно създадени
                .filter(event -> event.getStart() != null)
                .filter(event -> !event.getStart().isBefore(startDateTime) && !event.getStart().isAfter(endDateTime))
                .filter(event -> event.getLeaveType() == null) // Изключваме отпуски
                .collect(Collectors.toList());
    }

    /**
     * ФУНКЦИЯ: Избира работни дни, спазвайки ограниченията
     * - Максимум 6 последователни работни дни
     * - Минимум 2 почивни дни на седмица
     */
    private List<LocalDate> selectWorkDaysWithConstraints(List<LocalDate> availableDays, int daysNeeded, Set<LocalDate> occupiedDates) {
        List<LocalDate> selectedDays = new ArrayList<>();
        Collections.shuffle(availableDays); // Случайно разбъркване за по-добро разпределение

        for (LocalDate day : availableDays) {
            if (selectedDays.size() >= daysNeeded) {
                break;
            }

            // Проверяваме дали добавянето на този ден нарушава ограниченията
            if (isValidWorkDay(day, selectedDays, occupiedDates)) {
                selectedDays.add(day);
            }
        }

        // Сортираме по дата за по-лесно четене
        selectedDays.sort(LocalDate::compareTo);
        return selectedDays;
    }

    /**
     * ФУНКЦИЯ: Проверява дали дадения ден може да бъде работен без нарушаване на ограниченията
     */
    private boolean isValidWorkDay(LocalDate candidateDay, List<LocalDate> selectedDays, Set<LocalDate> occupiedDates) {
        // Комбинираме избраните дни със заетите дни за пълна картина
        Set<LocalDate> allWorkDays = new HashSet<>(selectedDays);
        allWorkDays.addAll(occupiedDates);
        allWorkDays.add(candidateDay);

        // Проверяваме за максимум 6 последователни работни дни
        return !hasMoreThanSixConsecutiveDays(allWorkDays);
    }

    /**
     * ФУНКЦИЯ: Проверява дали има повече от 6 последователни работни дни
     */
    private boolean hasMoreThanSixConsecutiveDays(Set<LocalDate> workDays) {
        if (workDays.size() < 7) {
            return false;
        }

        List<LocalDate> sortedDays = new ArrayList<>(workDays);
        sortedDays.sort(LocalDate::compareTo);

        int consecutiveCount = 1;
        for (int i = 1; i < sortedDays.size(); i++) {
            if (sortedDays.get(i).isEqual(sortedDays.get(i-1).plusDays(1))) {
                consecutiveCount++;
                if (consecutiveCount > 6) {
                    return true;
                }
            } else {
                consecutiveCount = 1;
            }
        }

        return false;
    }

    /**
     * ФУНКЦИЯ: Създава балансирани смени за избраните дни
     */
    private List<Event> createBalancedShifts(Employee employee, List<LocalDate> selectedDays) {
        List<Event> shifts = new ArrayList<>();
        ShiftType[] shiftTypes = ShiftType.values();

        for (int i = 0; i < selectedDays.size(); i++) {
            LocalDate workDay = selectedDays.get(i);

            // Циклично разпределяне на смените за баланс
            ShiftType shiftType = shiftTypes[i % shiftTypes.length];

            // Създаваме смяната
            Event shift = new Event();
            shift.setTitle(employee.getName().split(" ")[0]); // Първото име
            shift.setStart(workDay.atTime(shiftType.getStartTime()));
            shift.setEnd(workDay.atTime(shiftType.getEndTime()));
            shift.setActivity("Auto-generated"); // Може да се персонализира
            shift.setEmployee(employee);
            shift.setIsAutoGenerated(true); // ВАЖНО: Маркираме като автоматично генерирана

            shifts.add(shift);

            System.out.println(String.format("📋 Създадена смяна: %s в %s (%s)",
                    workDay, shiftType.getName(), employee.getName()));
        }

        return shifts;
    }
}