package com.example.schedule.service;

import com.example.schedule.entity.Activity;
import com.example.schedule.entity.Employee;
import com.example.schedule.entity.Event;
import com.example.schedule.repository.EmployeeRepository;
import com.example.schedule.repository.EventRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.Map;
import java.util.stream.Collectors;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.DayOfWeek;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class ScheduleGeneratorService {

    @Autowired
    private EmployeeRepository employeeRepository;

    @Autowired
    private EventRepository eventRepository;

    // ДОБАВИ ТОЗИ РЕД:
    @Autowired
    private WeeklyScheduleService weeklyScheduleService;

    @Autowired
    private ActivityService activityService;

    // Константи за смените
    private static final LocalTime FIRST_SHIFT_START = LocalTime.of(6, 0);
    private static final LocalTime FIRST_SHIFT_END = LocalTime.of(14, 30);

    private static final LocalTime SECOND_SHIFT_START = LocalTime.of(13, 30);
    private static final LocalTime SECOND_SHIFT_END = LocalTime.of(22, 0);

    private static final LocalTime MIDDLE_SHIFT_START = LocalTime.of(9, 30);
    private static final LocalTime MIDDLE_SHIFT_END = LocalTime.of(18, 0);

    // Константи за правилата
    private static final double SHIFT_HOURS = 8.5; // Часове на смяна
    private static final int MAX_CONSECUTIVE_DAYS = 6; // Максимум последователни дни

    // Енум за типовете смени
    public enum ShiftType {
        FIRST("First Shift", FIRST_SHIFT_START, FIRST_SHIFT_END),
        SECOND("Second Shift", SECOND_SHIFT_START, SECOND_SHIFT_END),
        MIDDLE("Middle Shift", MIDDLE_SHIFT_START, MIDDLE_SHIFT_END);

        private final String name;
        private final LocalTime startTime;
        private final LocalTime endTime;

        ShiftType(String name, LocalTime startTime, LocalTime endTime) {
            this.name = name;
            this.startTime = startTime;
            this.endTime = endTime;
        }

        public String getName() { return name; }
        public LocalTime getStartTime() { return startTime; }
        public LocalTime getEndTime() { return endTime; }
    }

    /**
     * ГЛАВНА ФУНКЦИЯ: Генерира автоматично график със СТРОГИ правила
     */
    @Transactional
    public int generateMonthlySchedule(int year, int month) {
        System.out.println("🚀 === ЗАПОЧВА ОПРОСТЕНО ГЕНЕРИРАНЕ НА ГРАФИК ===");
        System.out.println(String.format("📅 Период: %02d/%d", month, year));

        // СТЪПКА 1: Подготовка
        List<Employee> allEmployees = employeeRepository.findAll();
        if (allEmployees.isEmpty()) {
            System.out.println("❌ Няма налични служители");
            return 0;
        }

        List<LocalDate> allDaysInMonth = generateAllDaysForMonth(year, month);
        Map<LocalDate, List<Event>> existingShifts = getExistingManualShiftsByDate(year, month);

        // Изтриваме стари автоматично генерирани смени
        deleteAutoGeneratedShiftsForMonth(year, month);

        System.out.println(String.format("👥 Служители: %d, 📅 Дни: %d, 📌 Ръчни смени: %d",
                allEmployees.size(), allDaysInMonth.size(),
                existingShifts.values().stream().mapToInt(List::size).sum()));

        // СТЪПКА 2: Създаваме прост tracker
        SimpleScheduleTracker tracker = new SimpleScheduleTracker(allEmployees, allDaysInMonth);

        // Добавяме съществуващите ръчни смени
        addExistingShiftsToTracker(tracker, existingShifts);

        // СТЪПКА 3: Основно планиране - ден по ден със строги правила
        planBasicSchedule(tracker, allDaysInMonth);

        // СТЪПКА 4: Проверяваме договорните часове и добавяме смени ако е нужно
        ensureMinimumHours(tracker, allDaysInMonth);

        // СТЪПКА 5: Създаваме и записваме Event обектите
        List<Event> generatedEvents = createEventsFromTracker(tracker);
        eventRepository.saveAll(generatedEvents);

        // ДОБАВИ ТЕЗИ РЕДОВЕ:
        // СТЪПКА 5.5: Обновяваме weekly_schedule таблицата за всички служители
        System.out.println("🔄 Updating weekly schedule data for all employees...");
        for (Employee employee : allEmployees) {
            try {
                weeklyScheduleService.getWeeklyScheduleForMonth(employee.getId(), year, month);
                System.out.println(String.format("✅ Updated weekly schedule for %s", employee.getName()));
            } catch (Exception e) {
                System.err.println(String.format("❌ Failed to update weekly schedule for %s: %s",
                        employee.getName(), e.getMessage()));
            }
        }

// СТЪПКА 6: Финални статистики
        logFinalResults(tracker, generatedEvents);

        System.out.println(String.format("🎯 ГЕНЕРИРАНЕТО ЗАВЪРШИ! Създадени смени: %d", generatedEvents.size()));
        return generatedEvents.size();
    }

    /**
     * ЕТАП 3: Основно планиране ден по ден със строги правила
     */
    private void planBasicSchedule(SimpleScheduleTracker tracker, List<LocalDate> allDays) {
        System.out.println("📅 === ОСНОВНО ПЛАНИРАНЕ (1 СМЯНА НА ДЕН MAX) ===");

        // Създаваме ротационни почивни дни
        assignRotationalRestDays(tracker, allDays);

        // Планираме ден по ден
        for (LocalDate day : allDays) {
            planSingleDay(tracker, day);
        }
    }

    /**
     * ФУНКЦИЯ: Създава ротационни почивни дни СПОРЕД ДОГОВОРА
     */
    private void assignRotationalRestDays(SimpleScheduleTracker tracker, List<LocalDate> allDays) {
        System.out.println("🔄 Създаване на почивни дни според договора...");

        List<Employee> employees = tracker.getAllEmployees();

        for (int i = 0; i < employees.size(); i++) {
            Employee emp = employees.get(i);
            int contractHours = getContractHours(emp);

            // Изчисляваме колко дни трябва да работи според договора
            double monthlyHours = calculateRequiredMonthlyHours(emp);
            int maxWorkDaysPerMonth = (int) Math.ceil(monthlyHours / SHIFT_HOURS);
            int restDaysNeeded = allDays.size() - maxWorkDaysPerMonth;

            System.out.println(String.format("👤 %s (договор %dч): може макс %d работни дни, трябва %d почивни дни",
                    emp.getName(), contractHours, maxWorkDaysPerMonth, restDaysNeeded));

            // Създаваме ротационен шаблон за почивки според договора
            assignRestDaysForEmployee(tracker, emp, allDays, restDaysNeeded, i);
        }
    }

    /**
     * ПОМОЩНА ФУНКЦИЯ: Задава почивни дни за конкретен служител
     */
    private void assignRestDaysForEmployee(SimpleScheduleTracker tracker, Employee emp,
                                           List<LocalDate> allDays, int restDaysNeeded, int employeeIndex) {

        // Различни базови шаблони за ротация
        List<DayOfWeek> basePattern;
        switch (employeeIndex % 7) {
            case 0: basePattern = Arrays.asList(DayOfWeek.SATURDAY, DayOfWeek.SUNDAY); break;
            case 1: basePattern = Arrays.asList(DayOfWeek.MONDAY, DayOfWeek.TUESDAY); break;
            case 2: basePattern = Arrays.asList(DayOfWeek.WEDNESDAY, DayOfWeek.THURSDAY); break;
            case 3: basePattern = Arrays.asList(DayOfWeek.FRIDAY, DayOfWeek.SATURDAY); break;
            case 4: basePattern = Arrays.asList(DayOfWeek.SUNDAY, DayOfWeek.MONDAY); break;
            case 5: basePattern = Arrays.asList(DayOfWeek.TUESDAY, DayOfWeek.WEDNESDAY); break;
            default: basePattern = Arrays.asList(DayOfWeek.THURSDAY, DayOfWeek.FRIDAY); break;
        }

        Set<LocalDate> restDays = new HashSet<>();

        // Първо добавяме базовия шаблон (2 дни седмично)
        for (LocalDate day : allDays) {
            if (basePattern.contains(day.getDayOfWeek())) {
                restDays.add(day);
            }
        }

        // Ако трябват повече почивни дни (за 4ч и 6ч договори), добавяме още
        if (restDays.size() < restDaysNeeded) {
            List<LocalDate> remainingDays = allDays.stream()
                    .filter(day -> !restDays.contains(day))
                    .collect(Collectors.toList());

            Collections.shuffle(remainingDays);

            int additionalDaysNeeded = restDaysNeeded - restDays.size();
            for (int i = 0; i < additionalDaysNeeded && i < remainingDays.size(); i++) {
                restDays.add(remainingDays.get(i));
            }
        }

        // Задаваме почивните дни
        for (LocalDate restDay : restDays) {
            tracker.setRestDay(emp, restDay);
        }

        System.out.println(String.format("   📅 %s: %d почивни дни от %d",
                emp.getName(), restDays.size(), allDays.size()));
    }

    /**
     * КЛЮЧОВА ФУНКЦИЯ: Планира един ден със СТРОГИ правила
     */
    private void planSingleDay(SimpleScheduleTracker tracker, LocalDate day) {
        // СТЪПКА 1: Намираме кои служители могат да работят
        List<Employee> availableEmployees = new ArrayList<>();

        for (Employee emp : tracker.getAllEmployees()) {
            if (canEmployeeWorkOnDay(tracker, emp, day)) {
                availableEmployees.add(emp);
            }
        }

        if (availableEmployees.isEmpty()) {
            System.out.println(String.format("⚠️ %s: Няма налични служители!", day));
            return;
        }

        // СТЪПКА 2: Разбъркваме за справедливост
        Collections.shuffle(availableEmployees);

        // СТЪПКА 3: Определяме колко служители трябват (3-6)
        int employeesNeeded = Math.max(3, Math.min(availableEmployees.size(), 6));

        // СТЪПКА 4: Разделяме служителите по смени които могат да работят
        List<Employee> canWorkFirst = filterByAllowedShift(tracker, availableEmployees, day, ShiftType.FIRST);
        List<Employee> canWorkSecond = filterByAllowedShift(tracker, availableEmployees, day, ShiftType.SECOND);
        List<Employee> canWorkMiddle = filterByAllowedShift(tracker, availableEmployees, day, ShiftType.MIDDLE);

        // СТЪПКА 5: Разпределяме смените балансирано
        int middleAssigned = assignShifts(tracker, day, canWorkMiddle, ShiftType.MIDDLE, 1); // Винаги поне 1
        int remaining = employeesNeeded - middleAssigned;

        int firstNeeded = remaining / 2;
        int secondNeeded = remaining - firstNeeded;

        int firstAssigned = assignShifts(tracker, day, canWorkFirst, ShiftType.FIRST, firstNeeded);
        int secondAssigned = assignShifts(tracker, day, canWorkSecond, ShiftType.SECOND, secondNeeded);

        System.out.println(String.format("📅 %s: %d първи, %d втори, %d междинни",
                day, firstAssigned, secondAssigned, middleAssigned));
    }

    /**
     * ПОМОЩНА ФУНКЦИЯ: Филтрира служители които могат да работят конкретна смяна
     */
    private List<Employee> filterByAllowedShift(SimpleScheduleTracker tracker, List<Employee> employees,
                                                LocalDate day, ShiftType shiftType) {
        return employees.stream()
                .filter(emp -> canWorkSpecificShift(tracker, emp, day, shiftType))
                .collect(Collectors.toList());
    }

    /**
     * ПОМОЩНА ФУНКЦИЯ: Разпределя смени на служители
     */
    private int assignShifts(SimpleScheduleTracker tracker, LocalDate day, List<Employee> candidates,
                             ShiftType shiftType, int needed) {
        int assigned = 0;
        for (Employee emp : candidates) {
            if (assigned >= needed) break;
            if (!tracker.hasShiftOnDay(emp, day)) {
                tracker.addShift(emp, day, shiftType);
                assigned++;
            }
        }
        return assigned;
    }

    /**
     * КРИТИЧНА ФУНКЦИЯ: Проверява дали служител може да работи в даден ден
     */
    private boolean canEmployeeWorkOnDay(SimpleScheduleTracker tracker, Employee emp, LocalDate day) {
        // Проверка 1: Почивен ден
        if (tracker.isRestDay(emp, day)) {
            return false;
        }

        // Проверка 2: Вече има смяна в деня
        if (tracker.hasShiftOnDay(emp, day)) {
            return false;
        }

        // Проверка 3: Максимум 6 последователни дни
        if (getConsecutiveWorkDays(tracker, emp, day) >= MAX_CONSECUTIVE_DAYS) {
            return false;
        }

        return true;
    }

    /**
     * КРИТИЧНА ФУНКЦИЯ: Проверява дали може да работи конкретна смяна
     * ПОДОБРЕНА с DEBUG логове
     */
    private boolean canWorkSpecificShift(SimpleScheduleTracker tracker, Employee emp, LocalDate day, ShiftType targetShift) {
        // Първо основните проверки
        if (!canEmployeeWorkOnDay(tracker, emp, day)) {
            return false;
        }

        // КРИТИЧНА ПРОВЕРКА: 12-часовото правило с предходния ден
        LocalDate previousDay = day.minusDays(1);
        ShiftType previousShift = tracker.getShiftForDay(emp, previousDay);

        if (previousShift != null) {
            boolean allowed = isShiftAllowedAfterPrevious(previousShift, targetShift);

            if (!allowed) {
                System.out.println(String.format("🚫 12h RULE VIOLATION: %s не може %s на %s след %s на %s",
                        emp.getName(), targetShift.getName(), day, previousShift.getName(), previousDay));
            }

            return allowed;
        }

        return true;
    }

    /**
     * КЛЮЧОВА ФУНКЦИЯ: 12-часовото правило - строго спазване с DEBUG
     */
    private boolean isShiftAllowedAfterPrevious(ShiftType previousShift, ShiftType targetShift) {
        // ПРАВИЛО 1: След втора смяна (до 22:00) → САМО втора смяна (13:30+) следващия ден
        if (previousShift == ShiftType.SECOND) {
            boolean allowed = (targetShift == ShiftType.SECOND);
            System.out.println(String.format("🔍 12h CHECK: След %s → %s = %s",
                    previousShift.getName(), targetShift.getName(), allowed ? "✅ РАЗРЕШЕНО" : "❌ ЗАБРАНЕНО"));
            return allowed;
        }

        // ПРАВИЛО 2: След междинна/първа смяна → всякаква смяна е ОК
        System.out.println(String.format("🔍 12h CHECK: След %s → %s = ✅ РАЗРЕШЕНО",
                previousShift.getName(), targetShift.getName()));
        return true;
    }

    /**
     * ПОМОЩНА ФУНКЦИЯ: Изчислява последователни работни дни
     */
    private int getConsecutiveWorkDays(SimpleScheduleTracker tracker, Employee emp, LocalDate startDay) {
        int count = 0;
        LocalDate day = startDay.minusDays(1); // Започваме от деня преди

        // Броим назад колко дни подред работи
        while (day != null && tracker.hasShiftOnDay(emp, day)) {
            count++;
            day = day.minusDays(1);
            if (count >= 10) break; // Защита
        }

        return count;
    }

    /**
     * ЕТАП 4: Осигурява минималните договорни часове
     */
    private void ensureMinimumHours(SimpleScheduleTracker tracker, List<LocalDate> allDays) {
        System.out.println("💼 === ПРОВЕРКА НА ДОГОВОРНИТЕ ЧАСОВЕ ===");

        for (Employee emp : tracker.getAllEmployees()) {
            double requiredHours = calculateRequiredMonthlyHours(emp);
            double currentHours = tracker.getTotalHoursForEmployee(emp);

            System.out.println(String.format("👤 %s (договор %dч): има %.1fч, трябва %.1fч",
                    emp.getName(), getContractHours(emp), currentHours, requiredHours));

            if (currentHours < requiredHours) {
                double missingHours = requiredHours - currentHours;
                addShiftsForMissingHours(tracker, emp, missingHours, allDays);
            }
        }
    }

    /**
     * ФУНКЦИЯ: Изчислява нужните месечни часове (опростено)
     */
    private double calculateRequiredMonthlyHours(Employee emp) {
        int contractHours = getContractHours(emp);

        // Опростено изчисление: 1 месец = 4 седмици
        // 4ч договор = 20ч седмично × 4 = 80ч месечно
        // 6ч договор = 30ч седмично × 4 = 120ч месечно
        // 8ч договор = 40ч седмично × 4 = 160ч месечно
        return (contractHours * 5) * 4; // 5 дни седмично × 4 седмици
    }

    /**
     * ПОМОЩНА ФУНКЦИЯ: Връща договорните часове на служител
     */
    private int getContractHours(Employee emp) {
        return emp.getHourlyRate() != null ? emp.getHourlyRate() : 8;
    }

    /**
     * ФУНКЦИЯ: Добавя смени за покриване на недостигащи часове
     * ПОДОБРЕНА с СТРОГИ проверки за 12-часовото правило
     */
    private void addShiftsForMissingHours(SimpleScheduleTracker tracker, Employee emp,
                                          double missingHours, List<LocalDate> allDays) {
        System.out.println(String.format("🔧 Добавяне на %.1f часа за %s", missingHours, emp.getName()));

        int shiftsNeeded = (int) Math.ceil(missingHours / SHIFT_HOURS);
        int shiftsAdded = 0;

        // Търсим дни където може да добавим смени
        for (LocalDate day : allDays) {
            if (shiftsAdded >= shiftsNeeded) break;

            // Ако е почивен ден, опитваме се да го направим работен
            if (tracker.isRestDay(emp, day)) {
                ShiftType bestShift = findBestShiftForDayWithStrictChecks(tracker, emp, day);
                if (bestShift != null) {
                    // ДОПЪЛНИТЕЛНА ПРОВЕРКА: Спазва ли 12-часовото правило?
                    if (canWorkSpecificShift(tracker, emp, day, bestShift)) {
                        tracker.removeRestDay(emp, day);
                        tracker.addShift(emp, day, bestShift);
                        shiftsAdded++;

                        System.out.println(String.format("➕ Добавена смяна: %s на %s (%s)",
                                emp.getName(), day, bestShift.getName()));
                    } else {
                        System.out.println(String.format("🚫 НЕ добавяме смяна за %s на %s - нарушава 12h правилото",
                                emp.getName(), day));
                    }
                }
            }
        }

        if (shiftsAdded < shiftsNeeded) {
            System.out.println(String.format("⚠️ %s: Добавени само %d от %d нужни смени (заради 12h правилото)",
                    emp.getName(), shiftsAdded, shiftsNeeded));
        }
    }

    /**
     * ФУНКЦИЯ: Намира най-подходящата смяна за деня със СТРОГИ проверки
     */
    private ShiftType findBestShiftForDayWithStrictChecks(SimpleScheduleTracker tracker, Employee emp, LocalDate day) {
        // Проверяваме всички типове смени със строги 12-часови проверки
        if (canWorkSpecificShift(tracker, emp, day, ShiftType.MIDDLE)) {
            return ShiftType.MIDDLE;
        }
        if (canWorkSpecificShift(tracker, emp, day, ShiftType.FIRST)) {
            return ShiftType.FIRST;
        }
        if (canWorkSpecificShift(tracker, emp, day, ShiftType.SECOND)) {
            return ShiftType.SECOND;
        }
        return null;
    }

    // ============================================================================
    // ПОМОЩНИ ФУНКЦИИ ЗА ОБРАБОТКА НА ДАННИ
    // ============================================================================

    private List<LocalDate> generateAllDaysForMonth(int year, int month) {
        List<LocalDate> allDays = new ArrayList<>();
        LocalDate date = LocalDate.of(year, month, 1);
        LocalDate endOfMonth = date.withDayOfMonth(date.lengthOfMonth());

        while (!date.isAfter(endOfMonth)) {
            allDays.add(date);
            date = date.plusDays(1);
        }
        return allDays;
    }

    private Map<LocalDate, List<Event>> getExistingManualShiftsByDate(int year, int month) {
        LocalDate startOfMonth = LocalDate.of(year, month, 1);
        LocalDate endOfMonth = startOfMonth.withDayOfMonth(startOfMonth.lengthOfMonth());

        LocalDateTime startDateTime = startOfMonth.atStartOfDay();
        LocalDateTime endDateTime = endOfMonth.atTime(23, 59, 59);

        List<Event> manualEvents = eventRepository.findAll().stream()
                .filter(event -> event.getIsAutoGenerated() == null || !event.getIsAutoGenerated())
                .filter(event -> event.getStart() != null)
                .filter(event -> !event.getStart().isBefore(startDateTime) && !event.getStart().isAfter(endDateTime))
                .filter(event -> event.getLeaveType() == null)
                .collect(Collectors.toList());

        return manualEvents.stream()
                .collect(Collectors.groupingBy(event -> event.getStart().toLocalDate()));
    }

    private void addExistingShiftsToTracker(SimpleScheduleTracker tracker,
                                            Map<LocalDate, List<Event>> existingShifts) {
        for (Map.Entry<LocalDate, List<Event>> entry : existingShifts.entrySet()) {
            LocalDate date = entry.getKey();
            for (Event event : entry.getValue()) {
                ShiftType shiftType = determineShiftType(event);
                tracker.addExistingShift(event.getEmployee(), date, shiftType);
            }
        }
    }

    private ShiftType determineShiftType(Event event) {
        LocalTime startTime = event.getStart().toLocalTime();

        if (startTime.equals(FIRST_SHIFT_START)) return ShiftType.FIRST;
        if (startTime.equals(SECOND_SHIFT_START)) return ShiftType.SECOND;
        if (startTime.equals(MIDDLE_SHIFT_START)) return ShiftType.MIDDLE;

        if (startTime.isBefore(LocalTime.of(10, 0))) return ShiftType.FIRST;
        if (startTime.isAfter(LocalTime.of(13, 0))) return ShiftType.SECOND;
        return ShiftType.MIDDLE;
    }

    /**
     * ПОПРАВЕН МЕТОД: Създава Event обекти от ScheduleTracker данните
     * НОВО: Използва Activity entity вместо String
     *
     * @param tracker обект със генерираните смени
     * @return списък с Event обекти готови за запис в базата
     */
    private List<Event> createEventsFromTracker(SimpleScheduleTracker tracker) {
        System.out.println("🔄 Creating events from tracker data...");
        List<Event> events = new ArrayList<>();

        // СТЪПКА 1: Зареждаме всички активни activities за да ги използваме
        List<Activity> availableActivities = activityService.getAllActiveActivities();
        System.out.println("📋 Available activities: " + availableActivities.size());

        // СТЪПКА 2: Създаваме мапа за бързо намиране на activity по име
        Map<String, Activity> activityMap = availableActivities.stream()
                .collect(Collectors.toMap(Activity::getName, activity -> activity));

        for (Employee emp : tracker.getAllEmployees()) {
            Map<LocalDate, ShiftType> shifts = tracker.getGeneratedShiftsForEmployee(emp);
            System.out.println("👤 Processing " + shifts.size() + " shifts for employee: " + emp.getName());

            for (Map.Entry<LocalDate, ShiftType> entry : shifts.entrySet()) {
                LocalDate date = entry.getKey();
                ShiftType shiftType = entry.getValue();

                Event event = new Event();
                event.setTitle(emp.getName().split(" ")[0]);
                event.setStart(date.atTime(shiftType.getStartTime()));
                event.setEnd(date.atTime(shiftType.getEndTime()));
                event.setEmployee(emp);
                event.setIsAutoGenerated(true);

                // НОВА ЛОГИКА: Намираме подходяща Activity за този ShiftType
                Activity assignedActivity = findActivityForShiftType(shiftType, activityMap);

                if (assignedActivity != null) {
                    event.setActivity(assignedActivity);
                    System.out.println("🎯 Assigned activity: " + assignedActivity.getName() +
                            " for shift: " + shiftType.getName());
                } else {
                    // Ако няма подходяща activity, може да оставим null или да използваме default
                    System.out.println("⚠️ No suitable activity found for shift type: " + shiftType.getName());
                    // event.setActivity(null); // Оставяме null

                    // ИЛИ използваме default activity ако имаш такава:
                    Activity defaultActivity = activityMap.get("General Work"); // Примерно име
                    if (defaultActivity != null) {
                        event.setActivity(defaultActivity);
                        System.out.println("🔄 Using default activity: " + defaultActivity.getName());
                    }
                }

                events.add(event);
            }
        }

        System.out.println("✅ Created " + events.size() + " events from tracker data");
        return events;
    }

    /**
     * ПОМОЩЕН МЕТОД: Намира подходяща Activity за даден ShiftType
     * Можеш да адаптираш логиката според твоите нужди
     *
     * @param shiftType типа на смяната
     * @param activityMap мапа с налични activities
     * @return подходяща Activity или null
     */
    private Activity findActivityForShiftType(ShiftType shiftType, Map<String, Activity> activityMap) {
        String shiftName = shiftType.getName().toLowerCase();

        // ЛОГИКА 1: Директно мапиране по име
        if (activityMap.containsKey(shiftType.getName())) {
            return activityMap.get(shiftType.getName());
        }

        // ЛОГИКА 2: Мапиране по ключови думи в името на смяната
        if (shiftName.contains("morning") || shiftName.contains("day")) {
            // За сутрешни/дневни смени използваме Cashier или Stock Replenishment
            return activityMap.getOrDefault("Cashier", activityMap.get("Stock Replenishment"));
        }

        if (shiftName.contains("evening") || shiftName.contains("night")) {
            // За вечерни смени използваме Stock Management или Freshness Manager
            return activityMap.getOrDefault("Stock Management Manager", activityMap.get("Freshness Manager"));
        }

        if (shiftName.contains("manager") || shiftName.contains("leader")) {
            // За ръководни смени
            return activityMap.get("Shift Leader");
        }

        // ЛОГИКА 3: Default activity (първата налична)
        if (!activityMap.isEmpty()) {
            Activity defaultActivity = activityMap.values().iterator().next();
            System.out.println("🔄 Using default activity: " + defaultActivity.getName() +
                    " for shift type: " + shiftType.getName());
            return defaultActivity;
        }

        // Ако няма никакви activities в базата
        System.out.println("❌ No activities available in database!");
        return null;
    }

    private void deleteAutoGeneratedShiftsForMonth(int year, int month) {
        LocalDate startOfMonth = LocalDate.of(year, month, 1);
        LocalDate endOfMonth = startOfMonth.withDayOfMonth(startOfMonth.lengthOfMonth());

        LocalDateTime startDateTime = startOfMonth.atStartOfDay();
        LocalDateTime endDateTime = endOfMonth.atTime(23, 59, 59);

        List<Event> autoGeneratedEvents = eventRepository.findAll().stream()
                .filter(event -> event.getIsAutoGenerated() != null && event.getIsAutoGenerated())
                .filter(event -> event.getStart() != null)
                .filter(event -> !event.getStart().isBefore(startDateTime) && !event.getStart().isAfter(endDateTime))
                .collect(Collectors.toList());

        if (!autoGeneratedEvents.isEmpty()) {
            eventRepository.deleteAll(autoGeneratedEvents);
            System.out.println(String.format("🗑️ Изтрити %d стари автоматично генерирани смени", autoGeneratedEvents.size()));
        }
    }

    private void logFinalResults(SimpleScheduleTracker tracker, List<Event> generatedEvents) {
        System.out.println("\n📊 === ФИНАЛНИ РЕЗУЛТАТИ (ОПРОСТЕНИ) ===");

        for (Employee emp : tracker.getAllEmployees()) {
            double totalHours = tracker.getTotalHoursForEmployee(emp);
            int workDays = tracker.getWorkDaysForEmployee(emp);
            int contractHours = getContractHours(emp);
            double requiredHours = calculateRequiredMonthlyHours(emp);

            System.out.println(String.format("👤 %s (договор %dч): %.1fч от %.1fч, %d работни дни",
                    emp.getName(), contractHours, totalHours, requiredHours, workDays));
        }

        System.out.println(String.format("\n✅ Общо генерирани смени: %d", generatedEvents.size()));
    }

    // ============================================================================
    // ОПРОСТЕН КЛАС ЗА ПРОСЛЕДЯВАНЕ НА ГРАФИКА
    // ============================================================================

    /**
     * Много по-прост клас за проследяване на графика
     * Гарантира: МАКСИМУМ 1 СМЯНА НА ДЕН за служител
     */
    public static class SimpleScheduleTracker {
        private List<Employee> employees;
        private Map<Employee, Set<LocalDate>> restDays = new HashMap<>();
        private Map<Employee, Map<LocalDate, ShiftType>> existingShifts = new HashMap<>();
        private Map<Employee, Map<LocalDate, ShiftType>> generatedShifts = new HashMap<>();

        public SimpleScheduleTracker(List<Employee> employees, List<LocalDate> allDays) {
            this.employees = employees;
            for (Employee emp : employees) {
                restDays.put(emp, new HashSet<>());
                existingShifts.put(emp, new HashMap<>());
                generatedShifts.put(emp, new HashMap<>());
            }
        }

        // Методи за почивни дни
        public void setRestDay(Employee emp, LocalDate day) {
            restDays.get(emp).add(day);
        }

        public void removeRestDay(Employee emp, LocalDate day) {
            restDays.get(emp).remove(day);
        }

        public boolean isRestDay(Employee emp, LocalDate day) {
            return restDays.get(emp).contains(day);
        }

        // Методи за смени - ГАРАНТИРА МАКСИМУМ 1 СМЯНА НА ДЕН
        public void addExistingShift(Employee emp, LocalDate day, ShiftType shiftType) {
            if (hasShiftOnDay(emp, day)) {
                System.out.println(String.format("⚠️ WARNING: %s вече има смяна на %s!", emp.getName(), day));
                return;
            }
            existingShifts.get(emp).put(day, shiftType);
        }

        public void addShift(Employee emp, LocalDate day, ShiftType shiftType) {
            if (hasShiftOnDay(emp, day)) {
                System.out.println(String.format("⚠️ WARNING: %s вече има смяна на %s!", emp.getName(), day));
                return;
            }
            generatedShifts.get(emp).put(day, shiftType);
        }

        public boolean hasShiftOnDay(Employee emp, LocalDate day) {
            return existingShifts.get(emp).containsKey(day) || generatedShifts.get(emp).containsKey(day);
        }

        public ShiftType getShiftForDay(Employee emp, LocalDate day) {
            if (existingShifts.get(emp).containsKey(day)) {
                return existingShifts.get(emp).get(day);
            }
            return generatedShifts.get(emp).get(day);
        }

        // Методи за анализ
        public double getTotalHoursForEmployee(Employee emp) {
            int totalShifts = existingShifts.get(emp).size() + generatedShifts.get(emp).size();
            return totalShifts * SHIFT_HOURS;
        }

        public int getWorkDaysForEmployee(Employee emp) {
            Set<LocalDate> allWorkDays = new HashSet<>(existingShifts.get(emp).keySet());
            allWorkDays.addAll(generatedShifts.get(emp).keySet());
            return allWorkDays.size();
        }

        // Getters
        public List<Employee> getAllEmployees() {
            return employees;
        }

        public Map<LocalDate, ShiftType> getGeneratedShiftsForEmployee(Employee emp) {
            return generatedShifts.get(emp);
        }
    }
}