package com.example.schedule.controller;

import com.example.schedule.dto.EventDto;
import com.example.schedule.dto.WeeklyScheduleDto;
import com.example.schedule.entity.Activity;
import com.example.schedule.entity.Employee;
import com.example.schedule.entity.Event;
import com.example.schedule.exception.ValidationException;
import com.example.schedule.repository.EventRepository;
import com.example.schedule.repository.EmployeeRepository;
import com.example.schedule.service.ActivityService;
import com.example.schedule.service.ValidationService;
import com.example.schedule.service.WeeklyScheduleService;
import jakarta.transaction.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.Map;
import java.util.HashMap;

@RestController
@RequestMapping("/events")
@CrossOrigin(origins = "http://localhost:3000")  // Разрешава заявки от React/HTML
public class EventController {

    private final EventRepository eventRepository;
    private final EmployeeRepository employeeRepository;
    private final ValidationService validationService; // НОВА ЗАВИСИМОСТ
    private final WeeklyScheduleService weeklyScheduleService;
    private final ActivityService activityService;

    /**
     * Конструктор с всички dependencies
     * @param eventRepository - Repository за събития
     * @param employeeRepository - Repository за служители
     * @param validationService - Сервис за валидация
     */
    public EventController(EventRepository eventRepository,
                           EmployeeRepository employeeRepository,
                           ValidationService validationService,
                           WeeklyScheduleService weeklyScheduleService,
                           ActivityService activityService) { // НОВО
        this.eventRepository = eventRepository;
        this.employeeRepository = employeeRepository;
        this.validationService = validationService;
        this.weeklyScheduleService = weeklyScheduleService;
        this.activityService = activityService; // НОВО
    }



    /**
     * GET метод за извличане на всички събития
     * @return List<EventDto> - Списък с всички събития
     */
    @GetMapping
    public List<EventDto> getAllEvents() {
        return eventRepository.findAllEventDtos();
    }

    /**
     * ОБНОВЕН POST МЕТОД ЗА СЪЗДАВАНЕ НА СЪБИТИЕ С ВАЛИДАЦИЯ
     * Добавена е валидация на работните часове преди създаване на събитие
     *
     * @return ResponseEntity<Event> - Резултат от операцията
     */
    @PostMapping
    public ResponseEntity<?> createEvent(@RequestBody Map<String, Object> eventData) {
        System.out.println("📥 Получена заявка за създаване на събитие: " + eventData);

        try {
            // СТЪПКА 1: Създаваме нов Event обект
            Event event = new Event();

            // СТЪПКА 2: Задаваме основните полета
            event.setTitle((String) eventData.get("title"));

            // Парсираме датите
            if (eventData.get("start") != null) {
                event.setStart(LocalDateTime.parse((String) eventData.get("start")));
            }
            if (eventData.get("end") != null) {
                event.setEnd(LocalDateTime.parse((String) eventData.get("end")));
            }

            event.setLeaveType((String) eventData.get("leaveType"));
            event.setIsAutoGenerated(false);

            // СТЪПКА 3: Обработваме Employee - ПОПРАВЕНО
            Object employeeObj = eventData.get("employee");
            if (employeeObj == null) {
                return ResponseEntity.badRequest()
                        .body(createErrorResponse("Employee information is required"));
            }

            Long employeeId;
            if (employeeObj instanceof Map) {
                // Ако е Map (от по-сложни форми)
                Map<String, Object> employeeData = (Map<String, Object>) employeeObj;
                if (employeeData.get("id") == null) {
                    return ResponseEntity.badRequest()
                            .body(createErrorResponse("Employee ID is required"));
                }
                employeeId = Long.parseLong(employeeData.get("id").toString());
            } else {
                // Ако е директно число или string (от твоя frontend)
                employeeId = Long.parseLong(employeeObj.toString());
            }

            Optional<Employee> employeeOpt = employeeRepository.findById(employeeId);
            if (employeeOpt.isEmpty()) {
                return ResponseEntity.badRequest()
                        .body(createErrorResponse("Employee not found"));
            }

            Employee employee = employeeOpt.get();
            event.setEmployee(employee);

// СТЪПКА 4: Обработваме Activity - ПОПРАВЕНО
            Object activityObj = eventData.get("activity");
            if (activityObj != null) {
                Long activityId = null;

                if (activityObj instanceof Map) {
                    // Ако е Map
                    Map<String, Object> activityData = (Map<String, Object>) activityObj;
                    if (activityData.get("id") != null) {
                        activityId = Long.parseLong(activityData.get("id").toString());
                    }
                } else {
                    // Ако е директно число или string
                    activityId = Long.parseLong(activityObj.toString());
                }

                if (activityId != null) {
                    Optional<Activity> activityOpt = activityService.getActivityById(activityId);
                    if (activityOpt.isEmpty()) {
                        return ResponseEntity.badRequest()
                                .body(createErrorResponse("Activity not found with ID: " + activityId));
                    }

                    Activity activity = activityOpt.get();
                    event.setActivity(activity);
                    System.out.println("✅ Activity set: " + activity.getName() + " (ID: " + activity.getId() + ")");
                }
            } else {
                // Няма activity (отпуска)
                event.setActivity(null);
                System.out.println("ℹ️ No activity set (leave event)");
            }

            // СТЪПКА 5: Задаваме title ако не е зададен
            if (event.getTitle() == null || event.getTitle().trim().isEmpty()) {
                event.setTitle(employee.getName().split(" ")[0]);
            }

            System.out.println("💾 Final event before save: " + event.toString());

            // СТЪПКА 6: Валидация (ако имаш ValidationService)
            try {
                if (validationService != null) {
                    validationService.validateEvent(event);
                    System.out.println("✅ Event validation passed");
                }
            } catch (ValidationException e) {
                System.out.println("❌ Validation error: " + e.getMessage());
                return ResponseEntity.badRequest()
                        .body(createErrorResponse(e.getFirstError()));
            }

            // СТЪПКА 7: Записваме в базата
            Event savedEvent = eventRepository.save(event);
            System.out.println("✅ Event saved successfully with ID: " + savedEvent.getId());

            // СТЪПКА 8: Обновяваме седмичния график
            try {
                weeklyScheduleService.updateWeeklyScheduleForEvent(
                        employee.getId(),
                        savedEvent.getStart().toLocalDate()
                );
                System.out.println("✅ Weekly schedule updated successfully");
            } catch (Exception e) {
                System.err.println("⚠️ Warning: Could not update weekly schedule: " + e.getMessage());
            }

            return ResponseEntity.status(HttpStatus.CREATED).body(savedEvent);

        } catch (Exception e) {
            System.err.println("❌ Unexpected error creating event: " + e.getMessage());
            e.printStackTrace();
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(createErrorResponse("An unexpected error occurred: " + e.getMessage()));
        }
    }
    /**
     * GET метод за получаване на събитие по ID
     * @param id - ID на събитието
     * @return ResponseEntity<Event> - Събитието или 404
     */
    @GetMapping("/{id}")
    public ResponseEntity<Event> getEventById(@PathVariable Long id) {
        return eventRepository.findById(id)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * ОБНОВЕН PUT МЕТОД ЗА РЕДАКТИРАНЕ НА СЪБИТИЕ С ВАЛИДАЦИЯ
     * ПОПРАВЕНО: Приема Map<String, Object> вместо Event entity
     *
     * @param id - ID на събитието
     * @param eventData - Новите данни за събитието като Map
     * @return ResponseEntity<?> - Резултат от операцията
     */
    @PutMapping("/{id}")
    public ResponseEntity<?> updateEvent(@PathVariable Long id, @RequestBody Map<String, Object> eventData) {
        System.out.println("🔧 Получена заявка за редактиране на събитие с ID: " + id);
        System.out.println("📦 Update data received: " + eventData);

        try {
            // Проверяваме дали събитието съществува
            Optional<Event> existingOpt = eventRepository.findById(id);
            if (existingOpt.isEmpty()) {
                return ResponseEntity.notFound().build();
            }

            Event existing = existingOpt.get();
            System.out.println("✅ Found existing event: " + existing.getTitle());

            // СТЪПКА 1: Парсираме датите от frontend
            if (eventData.get("start") != null) {
                existing.setStart(LocalDateTime.parse((String) eventData.get("start")));
            }
            if (eventData.get("end") != null) {
                existing.setEnd(LocalDateTime.parse((String) eventData.get("end")));
            }

            // СТЪПКА 2: Обработваме activity (ПОПРАВЕНО за ID/NAME compatibility)
            Object activityObj = eventData.get("activity");
            if (activityObj != null && !activityObj.toString().trim().isEmpty()) {
                String activityValue = activityObj.toString();
                System.out.println("🎯 Looking for activity with value: " + activityValue);

                Optional<Activity> activityOpt = Optional.empty();

                // Първо опитваме като ID (ако е число)
                try {
                    Long activityId = Long.parseLong(activityValue);
                    activityOpt = activityService.getActivityById(activityId);
                    System.out.println("🔍 Tried as ID: " + activityId + " - Found: " + activityOpt.isPresent());
                } catch (NumberFormatException e) {
                    // Не е число, опитваме като име
                    System.out.println("🔍 Not a number, trying as name: " + activityValue);
                }

                // Ако не намерихме по ID, опитваме по име
                if (activityOpt.isEmpty()) {
                    activityOpt = activityService.getActivityByName(activityValue);
                    System.out.println("🔍 Tried as name: " + activityValue + " - Found: " + activityOpt.isPresent());
                }

                if (activityOpt.isPresent()) {
                    existing.setActivity(activityOpt.get());
                    System.out.println("✅ Activity updated to: " + activityOpt.get().getName());
                } else {
                    System.out.println("⚠️ Activity not found with value: " + activityValue);
                    // Не хвърляме грешка, просто оставяме старата activity
                }
            } else {
                // Няма activity - това е отпуска
                existing.setActivity(null);
                System.out.println("ℹ️ Activity cleared (leave event)");
            }

            // СТЪПКА 3: Обработваме leaveType
            String leaveType = (String) eventData.get("leaveType");
            existing.setLeaveType(leaveType);

            // СТЪПКА 4: Валидация преди запис
            try {
                if (validationService != null) {
                    validationService.validateEvent(existing, true); // true = isUpdate
                    System.out.println("✅ Event validation passed");
                }
            } catch (ValidationException e) {
                System.out.println("❌ Валидационна грешка при редактиране: " + e.getMessage());
                return ResponseEntity.badRequest()
                        .body(createErrorResponse(e.getFirstError()));
            }

            // СТЪПКА 5: Записваме промените
            Event savedEvent = eventRepository.save(existing);
            System.out.println("✅ Event updated successfully with ID: " + savedEvent.getId());

            // СТЪПКА 6: Обновяваме седмичния график
            try {
                weeklyScheduleService.updateWeeklyScheduleForEvent(
                        existing.getEmployee().getId(),
                        savedEvent.getStart().toLocalDate()
                );
                System.out.println("✅ Weekly schedule updated successfully");
            } catch (Exception e) {
                System.err.println("⚠️ Warning: Could not update weekly schedule: " + e.getMessage());
            }

            return ResponseEntity.ok(savedEvent);

        } catch (Exception e) {
            System.err.println("❌ Неочаквана грешка при редактиране: " + e.getMessage());
            e.printStackTrace();
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(createErrorResponse("An unexpected error occurred"));
        }
    }
    /**
     * DELETE метод за изтриване на събитие
     * @param id - ID на събитието
     * @return ResponseEntity<Void> - Резултат от операцията
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteEvent(@PathVariable Long id) {
        System.out.println("🗑️ Получена заявка за изтриване на събитие с ID: " + id);

        if (eventRepository.existsById(id)) {
            eventRepository.deleteById(id);
            System.out.println("✅ Събитието е изтрито успешно");
            return ResponseEntity.noContent().build();
        } else {
            System.out.println("❌ Събитието не е намерено");
            return ResponseEntity.notFound().build();
        }
    }

    /**
     * ПОМОЩНА ФУНКЦИЯ: Създава error response в правилния формат
     * @param message - Съобщението за грешка
     * @return Map<String, String> - Error response
     */
    private Map<String, String> createErrorResponse(String message) {
        Map<String, String> errorResponse = new HashMap<>();
        errorResponse.put("error", message);
        errorResponse.put("timestamp", LocalDateTime.now().toString());
        return errorResponse;
    }
    @GetMapping("/schedules")
    public List<WeeklyScheduleDto> getWeeklySchedules() {
        return weeklyScheduleService.getAllWeeklySchedules();
    }

}